### ISSUE TITLE
Some APBs failed validation and were unavailable

### ISSUE THREAD

**Issue by wenchma** [openshift/ansible-service-broker#1036]
## Bug: Some APBs failed validation and were unavailable

**What happened**:
```
"Spec [ postgresql-apb ] failed validation for the following reason: [ APB Spec version [1.0.0] out of bounds 1.0 <= 1.0 ]. It will not be made available."
"Spec [ mediawiki-apb ] failed validation for the following reason: [ APB Spec version [1.0.0] out of bounds 1.0 <= 1.0 ]. It will not be made available."
"Spec [ mysql-apb ] failed validation for the following reason: [ APB Spec version [1.0.0] out of bounds 1.0 <= 1.0 ]. It will not be made available."
"Spec [ mariadb-apb ] failed validation for the following reason: [ APB Spec version [1.0.0] out of bounds 1.0 <= 1.0 ]. It will not be made available."

```
**What you expected to happen**:
These APBs should be available.

**How to reproduce it**:
```
$ svcat sync broker ansible-service-broker
```

**Comment by djzager** [comment]
The latest APBs are now published with a semver compatible version field (that's why you see `1.0.0`). The latest broker is able to handle these APBs (as well as appropriately discover older ones with `version==1.0`). The latest APBs will likely fail validation against older versions of the broker.
