### ISSUE TITLE
Cluster admin role is required to run any APB on Minishift / OKD

### ISSUE THREAD

**Issue by ibuziuk** [openshift/ansible-service-broker#1056]
## Bug: Cluster admin role is required to run any APB on Minishift / OKD

**What happened**: When trying to run any APB e.g. mongo / postgreSQL provisioned services are failed to start with:

`The service is not yet ready. Error provisioning ServiceInstance of ClusterServiceClass (K8S: "e9c042c4925dd0c7c25ceca4f5179e1c" ExternalName: "dh-mongodb-apb") at ClusterServiceBroker "openshift-automation-service-broker": Status: 403; ErrorMessage: <nil>; Description: User does not have sufficient permissions; ResponseError: <nil>`

![image](https://user-images.githubusercontent.com/1461122/44454958-23c19c00-a5fd-11e8-9612-d1aa753ea55a.png)

And only after granting cluster admin rights APB is started succesfully:

`oc adm policy add-cluster-role-to-user cluster-admin developer`

**What you expected to happen**: it is expected that the default user without cluster admin priviliges would be to run APB

**How to reproduce it**: 
Originally the issue has been reproduced for che apb - https://github.com/ansibleplaybookbundle/eclipse-che-apb/issues/19
with the default configuration - https://github.com/ansibleplaybookbundle/eclipse-che-apb#requirements
`canary` tag was used in order to get the latest version of APB

**Comment by eivantsov** [comment]
I can reproduce it with Origin 3.9 + ansible service broker deployed as https://github.com/openshift/ansible-service-broker/blob/master/scripts/run_latest_build.sh, and OKD 3.10 (--enable=ansible-service-broker)

**Comment by ibuziuk** [comment]
@dymurray @djzager could you please comment, if it is expected that cluster admin role is required for user to run any APB? AFAIK, it used to work with the default privileges

**Comment by djzager** [comment]
@ibuziuk the short answer is that the `cluster-admin` role is not required for running APBs via the service catalog UI.

**Comment by ibuziuk** [comment]
@djzager thank you for looking into this:

1. minishift v1.20.0+53c500a
2. 3.10 / @eivantsov tried 3.9 and it also works only with cluster admin rights
3. 

> export MINISHIFT_ENABLE_EXPERIMENTAL=y && \
> minishift config set iso-url centos && \
> minishift start --memory=8gb --cpus=4 --disk-size=50g \
>                 --network-nameserver 8.8.8.8 \
>                 --openshift-version 3.10.0-rc.0 \
>                 --extra-clusterup-flags "--enable=service-catalog,router,registry,web-console,persistent-volumes,rhel-imagestreams,automation-service-broker"

4. We are using canary / most recent version of APB by changing the image tag to canary:

More details here -  https://github.com/ansibleplaybookbundle/eclipse-che-apb#requirements

============================================================
==           Creating Ansible Service Broker...           ==
============================================================
time="2018-08-02T17:43:29Z" level=info msg="Initializing clients..."
time="2018-08-02T17:43:29Z" level=debug msg="Connecting to Cluster"
time="2018-08-02T17:43:29Z" level=info msg="OpenShift version: v3.10.0-rc.0+e9069f9-48"
time="2018-08-02T17:43:29Z" level=debug msg="plugin for the network - "
time="2018-08-02T17:43:29Z" level=debug msg="unable to retrieve the network plugin, defaulting to not joining networks - clusternetworks.network.openshift.io \"default\" not found"
time="2018-08-02T17:43:29Z" level=info msg="Kubernetes version: v1.10.0+b81c8f8"
time="2018-08-02T17:43:29Z" level=debug msg="Connecting Dao"
time="2018-08-02T17:43:29Z" level=debug msg="Connecting Registry"

AFAIK, @eivantsov installed it on 3.9 with `--service-catalog=true`  via:

`curl https://raw.githubusercontent.com/openshift/ansible-service-broker/master/apb/install.yaml | oc create -f -`

and the result is the same - vanilla user can not start any apb:

> The service is not yet ready. Error provisioning ServiceInstance of ClusterServiceClass (K8S: "1882ffca5d72b1084e9107e3485f5066" ExternalName: "dh-eclipse-che-apb") at ClusterServiceBroker "openshift-automation-service-broker": Status: 403; ErrorMessage: <nil>; Description: User does not have sufficient permissions; ResponseError: <nil>

Hope this info would help to diagnose  the problem

**Comment by jwmatthews** [comment]
Ran through with below and saw an error with provision, perhaps possible auth issue?

$ minishift version
minishift v1.23.0+91235ee

export MINISHIFT_ENABLE_EXPERIMENTAL=y

minishift start --memory=8gb --cpus=4 --disk-size=20g \
                 --extra-clusterup-flags "--enable=service-catalog,router,registry,web-console,persistent-volumes,rhel-imagestreams,automation-service-broker"

Logged in as 'developer' into webu
Created 'jwm' namespace from webui logged in as 'developer'
 Attempted to provision mediawiki and postgres into 'jwm' namespace (logged in as 
developer')

Broker logs here:
  https://paste.fedoraproject.org/paste/f-CHlhhk4W2VskdCUj2n8w

**Comment by jwmatthews** [comment]
@djzager has identified removal of below is likely cause of issue:
  https://github.com/openshift/ansible-service-broker/pull/1016/files#diff-751bd0e50ddf51a85a77fc07d2060bcbL62

**Comment by djzager** [comment]
Looks like @ibuziuk that you guys may be suffering from an issue I caused right here https://github.com/openshift/ansible-service-broker/pull/1016/files#diff-751bd0e50ddf51a85a77fc07d2060bcbL62

I think that I must have really messed up a merge conflict, I'm not sure. My suspicion is that the lack of the `broker-user-auth` clusterrole was causing your issues.

**Comment by cunningt** [comment]
@djzager Is there any workaround to this issue for 3.10?

**Comment by djzager** [comment]
Install the broker made for 3.10 `curl https://raw.githubusercontent.com/openshift/ansible-service-broker/release-1.2/apb/install.yaml | oc create -f -`
