### ISSUE TITLE
ansibleplaybookbundle/apb-base:latest is broken

### ISSUE THREAD

**Issue by wtrocki** [openshift/ansible-service-broker#1073]
## Bug:

**What happened**:

Docker build fails with base image:
```
Step 6/8 : RUN ansible-galaxy install -r /opt/apb/actions/requirements.yml -p /opt/ansible/roles
---> Running in 02e8d0dac3ac
to see the full traceback, use -vvv
ERROR! Unexpected Exception, this is probably a bug: local variable 'stdout' referenced before assignment

```

**What you expected to happen**:

docker build passes

**How to reproduce it**:

1. Create sample apb
2. `apb prepare`
3. `docker build -t my-apb`

**Workaround**

Use nightly build or `FROM ansibleplaybookbundle/apb-base:sprint151` in Dockerfile.

**Comment by jmontleon** [comment]
Can you run ansible-galaxy with -vvv as it suggests so we can try to help determine what's going wrong, and or provide the Dockerfile if you're able so we can reproduce the issue.

**Comment by wtrocki** [comment]
That is the image and line that fails.
https://github.com/aerogearcatalog/data-sync-apb/blob/master/Dockerfile#L58

I would say that this is already fixed in the nightly build, so it's an matter of release.

**Comment by jmontleon** [comment]
This is: https://github.com/ansible/ansible/issues/43312
I've noticed git has dropped off some of our images lately. I think something dropped it as a dependency.

https://github.com/ansibleplaybookbundle/apb-base/pull/47
