### ISSUE TITLE
APIV2 adapter should accept token with name "token"

### ISSUE THREAD

**Issue by sebastien-prudhomme** [openshift/ansible-service-broker#1097]
## Bug:

**What happened**:

Trying to plug the broker to an internal Docker registry throught the "apiv2" adapter.

The token with the JSON field name "token" returned by the registry is not taken into account by the broker.

My registry doesn't implement the OAuth compatible name "access_token".

**What you expected to happen**:

The token should be accepted. See https://docs.docker.com/registry/spec/auth/token/

The broker only accepts OAuth tokens with the name "access_token" (see code in vendor/github.com/automationbroker/bundle-lib/registries/adapters https://github.com/automationbroker/bundle-lib/tree/master/registries/adapters).

**How to reproduce it**:

**Comment by sjahreis** [comment]
+1

**Comment by toplac** [comment]
see: https://github.com/automationbroker/bundle-lib/issues/174

**Comment by djzager** [comment]
@toplac are you saying that it is not in the `canary` tag of the image referenced in [this comment?](https://github.com/automationbroker/bundle-lib/issues/174#issuecomment-456149400)

**Comment by toplac** [comment]
Sorry, my comment should have been a hint, that this is fixed and available

**Comment by djzager** [comment]
:sunglasses: I must need coffee because I don't know how I read it any other way than you intended. The fix was brought into the broker via #1167

**Comment by djzager** [comment]
@eriknelson can we close this?

**Comment by sebastien-prudhomme** [comment]
The token part is OK now, thanks.
