### ISSUE TITLE
Broker ansible locks up determining if local_openshift_enabled

### ISSUE THREAD

**Issue by eriknelson** [openshift/ansible-service-broker#1105]
So it looks like under certain circumstances, the broker's ansible will completely lock up and hang when dynamically trying to determine if the local openshift adapter is enabled. Currently it uses the following line set in the defaults file:

`broker_local_openshift_enabled: "{{ ('image.openshift.io' in lookup('k8s', cluster_info='api_groups')) | bool }}"`

This task will hang as it tries to build the config: https://github.com/openshift/ansible-service-broker/blob/master/ansible_role/tasks/build_config.yml#L19

It's not clear to me exactly why or when this shows up, because I've seen it work in some circumstances and not in others. Right now, in the current OLM setup with catasb, you can't deploy a broker due to this issue unless you override the var with `broker_local_openshift_enabled: true`.

Here are the operator logs: https://gist.github.com/eriknelson/0b6d82a2de646374dd565f84ccbb9824

**Comment by jmontleon** [comment]
After some testing this is most like due to https://github.com/kubernetes-client/python/issues/653

We can pin the versions of python openshift and kubernetes until the underlying problem in python kubernetes is fixed. https://github.com/water-hole/ansible-operator/pull/56

**Comment by jmontleon** [comment]
Appears to be fixed in kubernetes 8.0.0 and openshift 0.8.0, which are both now released.

**Comment by fabianvf** [comment]
No that label seems appropriate

**Comment by xassan** [comment]
‘(..)’                                                                                                          IOOl                                                          .J L.

**Comment by jmontleon** [comment]
kubernetes 8.0.0 and openshift 0.8.0 have been built upstream and downstream and look to resolve the issue.
