### ISSUE TITLE
Unknown bootstrapper: localkube in Travis

### ISSUE THREAD

**Issue by bbaassssiiee** [openshift/ansible-service-broker#1110]
**This form is for bug reports and feature requests. Major features will go through a [spec process](https://github.com/openshift/ansible-service-broker/blob/master/CONTRIBUTING.md).**

## Bug: Travis build failed

**What happened**:

[https://travis-ci.org/openshift/ansible-service-broker/jobs/442841578](https://travis-ci.org/openshift/ansible-service-broker/jobs/442841578)

```
F1017 19:09:50.977431    4122 start.go:231] Error getting cluster bootstrapper: Unknown bootstrapper: localkube
```

**What you expected to happen**:
I fixed the linter, which changed upstream 6 days ago. I expected to fix the CI part. And the rest should work.

**How to reproduce it**:
Any Travis run.

**Comment by jmontleon** [comment]
I think we need to use an older minikuke for kubernetes 1.9.0. Should be fixed.

**Comment by jmontleon** [comment]
https://github.com/ansibleplaybookbundle/apb-test-shim/commit/f23cb8ee2d3bfab0773ae78f4353fc98df077fdf

**Comment by jmontleon** [comment]
This should be fixed.
