### ISSUE TITLE
fix travis.sh lint to output errors on failure

### ISSUE THREAD

**Issue by jmrodri** [openshift/ansible-service-broker#162]
The `scripts/travis.sh` script will eat linter errors. We should probably output the errors so that we can see them in the logs when it fails. Also print a suggestion to the user that they should run:

```
gofmt -d ./cmd
gofmt -d ./pkg
```

**Comment by shawn-hurley** [comment]
I also think that we should be using the linter and the vet tool.
https://github.com/golang/lint
https://golang.org/cmd/vet

**Comment by jmrodri** [comment]
@shawn-hurley wow, ran `golint pkg/...`, DEFINITELY have some work to do :)

**Comment by shawn-hurley** [comment]
I personally think that if most people turned on [metalinter](https://github.com/alecthomas/gometalinter) it does not take that long to run and set it up so it alerts you after a save and we could blow through these issues.
