### ISSUE TITLE
Refactor registry adapter code so that common registry functions don't overlap

### ISSUE THREAD

**Issue by dymurray** [openshift/ansible-service-broker#180]
Right now we have to different registry adapters for RHCC and Dockerhub. This is due to the fact that Dockerhub expects an authorization token workflow and RHCC has a different search mechanism. We found that under the hood both adapters are doing some introspection on the manifest for each image, they just both vary on how to find that manifest.

Moving forward we would like to consolidate the code so that a common registry package exists which does introspection on the manifest to return the spec and then individual adapters for sourcing the images to grab the manifests from.

**Comment by rthallisey** [comment]
Closing in favor of #256
