### ISSUE TITLE
Investigate removing dockerClient and dependency

### ISSUE THREAD

**Issue by eriknelson** [openshift/ansible-service-broker#227]
From discussion of #222 

> It's a vestige from when we pulled images before running then with oc run. I don't remember why we needed the pull in the first place, it's possible we never did. It's a use case entirely covered by the Pod pullPolicy. Huge bonus points if it means we can shed a dependency on docker entirely. We should definitely look into this, probably appropriate for an issue and follow up PR.

**Comment by shawn-hurley** [comment]
This was closed with #232
