### ISSUE TITLE
Consider singleton clients

### ISSUE THREAD

**Issue by eriknelson** [openshift/ansible-service-broker#229]
Arose out of #222 discussion.

It sounds like most people are in favor of singleton clients.

Considerations:
* Needs testing WRT concurrent usage of a since client instance (for all relevant clients).
* Should the instances be initialized and validated on first use, or on app startup? I think @shawn-hurley made some good arguments for the latter, fail fast and early.

**Comment by rthallisey** [comment]
I think it's better to validate the clients before we create the broker.  It's a simple pre-flight check to make sure your environment is in order.  I also think these checks could be added to the client package so we can reduce the size of app.go.

**Comment by eriknelson** [comment]
> I think it's better to validate the clients before we create the broker. It's a simple pre-flight check to make sure your environment is in order. I also think these checks could be added to the client package so we can reduce the size of app.go.

Agreed. When I was looking at refactoring things it seemed like there were a lot of blocks in `App.Start` that were written to instantiate/init/validate indirectly by just creating references. Think those init's and checks should be behind a func named appropriately like `InitAndValidate` called from `App.Start`, and then we can get rid of all of the random inits and exit 1 if anything blows up.

**Comment by shawn-hurley** [comment]
@eriknelson I think we can close this issue yes?
