### ISSUE TITLE
Remove apb/client.go Client struct and related refactoring.

### ISSUE THREAD

**Issue by eriknelson** [openshift/ansible-service-broker#231]
Arose out of #222 discussion.

Client struct in apb/client.go simply aggregates references to the various clients, which doesn't provide much value. It should be removed along with the `NewClient` constructor.

Additionally, pushing all the client related logic into the `clients` pkg brings into question whether `apb/client.go` is really an appropriate name for the file. Given the work being done (actually executing apb methods), consider a better name `RunApb(method, params)`.

**Comment by jmrodri** [comment]
Fixed by PR #238
