### ISSUE TITLE
Proposal: Support both Openshift and Kubernetes

### ISSUE THREAD

**Issue by rthallisey** [openshift/ansible-service-broker#233]
# Feature: Support other Clusters than OpenShift
The ansible-service-broker is currently OpenShift only because OpenShift has a few features that Kubernetes is still developing. The delta between OpenShift and Kubernetes is going to be a common occurrence so need a way to easily support both. I'm proposing that we can solve this by organizing our code paths into separate pieces and filling the gaps to meet the service-catalog specs:
- Kubernetes operations
- OpenShift operations
- Kubernetes hack operations that perform the actions done in 'OpenShift operations', but for Kubernetes

## Proposed work

1. ~~Split out all the clients into pkg/clients/~~
  1a. ~~https://github.com/openshift/ansible-service-broker/issues/213~~
  2a. ~~https://github.com/openshift/ansible-service-broker/pull/222~~
2. Split out all Cluster logic into a pkg/cluster/openshift.go and pkg/cluster/kubernetes.go
- Kubernetes is used for the majority of the broker actions while OpenShift a small number of actions. Let's break apart these code paths and call into a cluster pkg for cluster actions.
3. Create a pkg/cluster/kubernetes-hack.go that will do OpenShift specific functions the Kubernetes way
4. Use a Kubernetes solution to service accounts
  4a. https://github.com/openshift/ansible-service-broker/blob/master/pkg/apb/svc_acct.go
5. Change APBs so they support Kubernetes
  5a. https://github.com/fusor/apb-examples/issues/60
6. Remove all "oc" commands and replace them with Kubernetes and OpenShift client calls
  6a. https://github.com/openshift/ansible-service-broker/search?p=1&q=%22oc%22&type=&utf8=%E2%9C%93

**Comment by rthallisey** [comment]
I think git might've closed this.  Reopening to track more PR's

**Comment by ron1** [comment]
Was this closed prematurely?

**Comment by rthallisey** [comment]
Once #556 merged, the broker was able on kubernetes. 

If you want to use ansible to setup the broker & catalog on kubernetes see: https://github.com/fusor/catasb#openshift-or-kubernetes

If you want to use the template for the broker:  https://github.com/openshift/ansible-service-broker/blob/master/templates/k8s-ansible-service-broker.yaml.j2 and https://github.com/openshift/ansible-service-broker/blob/master/templates/k8s-template.py

**Comment by rthallisey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ability to run ASB in a pure Kubernetes clusters without OpenShift](https://trello.com/c/zkxHqA3d/360-ability-to-run-asb-in-a-pure-kubernetes-clusters-without-openshift)
