### ISSUE TITLE
Define the maximum privileges from an APB

### ISSUE THREAD

**Issue by rthallisey** [openshift/ansible-service-broker#269]
The broker's level of privileges is dependent on the level of privileges required by an APB.
``` Broker's Maximum Privilages = APB's Maximum Privilages```
Let's define the the maximum privileges an APB should have and see if it can be lowered below cluster-admin.

**Comment by tchughesiv** [comment]
project level "admin" rights _should_ be enough... we should limit the apb to its rights in its own project space.
e.g. https://github.com/fusor/apb-examples/blob/a2ac9a738657bbed89ecad0584a5ad25caa6c78a/jenkins-apb/Makefile#L33-L35

ASB should probably handle anything that requires cluster level rights, before deploying the apb to a project. The ASB should probably create a new (maybe random sa?) to assign to the APB, as not to potentially interfere w/ a project's existing SA's/settings.

**Comment by eriknelson** [comment]
This touches on our broader roadmap of APBs requesting privileges and the broker granting them via SAs. We need to allow for an operator to lock that down and blacklist requested abilities.

**Comment by LorbusChris** [comment]
I see usecases for APBs that would be exclusively aimed at system/cluster admins to deploy in/for/as their infrastructure, 

e.g. metrics, logging or [openshift-acme](https://github.com/tnozicka/openshift-acme).

So as for the title of this issue, I'd +1 a solution that makes maximum privs configurable on a per APB basis

**Comment by rthallisey** [comment]
Update on this: There has been a bunch of good work done by @shawn-hurley on APB privileges.  We require the broker config setting ```auto_escalate``` to be enabled in order to allow an APB to run with privileges above the service account it is running in.
