### ISSUE TITLE
pull policy configuration is NOT being honored

### ISSUE THREAD

**Issue by johnkim76** [openshift/ansible-service-broker#274]
The configurable pull policy is currently being set to 'Always', even though it's being configured to be set to "IfNotPresent".

**Comment by rthallisey** [comment]
Can you paste the logs from the broker?

**Comment by eriknelson** [comment]
I suspect this is a configuration issue and not actually a bug in the broker. Can you `oc exec` into a broker container that you think is not honoring the pull policy and post the `/etc/ansible-service-broker/config.yaml` contents?

**Comment by johnkim76** [comment]
@rthallisey @eriknelson I was trying to debug another issue, and with @jwmatthews help, we determined that the pull policy was being set to 'always'.  I'm using catasb (dev branch), and I've been deleting all the images before doing a reset of the environment.  Currenlty in a modified environment to complete another task, but I'll provide the requested info once I reset it back.

**Comment by eriknelson** [comment]
@johnkim76 Are you using the release-0.9 broker or the master broker?

**Comment by johnkim76** [comment]
@eriknelson I was using catasb which seemed to pull the latest image.  I was not using the broker source when I hit this issue.

**Comment by jwmatthews** [comment]
I can't reproduce with latest deployment from catasb 'dev' branch.

$ oc export pod apb-4a477dee-ee0d-4524-8c6d-dbbed6ddca04
apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: anyuid
  creationTimestamp: null
  name: apb-4a477dee-ee0d-4524-8c6d-dbbed6ddca04
spec:
  containers:
  - args:
    - provision
    - --extra-vars
    - '{"mediawiki_admin_pass":"password1","mediawiki_admin_user":"admin","mediawiki_db_schema":"mediawiki","mediawiki_site_lang":"en","mediawiki_site_name":"MediaWiki","namespace":"demo"}'
    image: ansibleplaybookbundle/mediawiki123-apb
    imagePullPolicy: IfNotPresent
name: apb
    resources: {}
    securityContext:
      capabilities:
        drop:
        - MKNOD
        - SYS_CHROOT
      privileged: false
      seLinuxOptions:
        level: s0:c9,c4
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: apb-4a477dee-ee0d-4524-8c6d-dbbed6ddca04-token-676hm
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: localhost
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    seLinuxOptions:
      level: s0:c9,c4
  serviceAccount: apb-4a477dee-ee0d-4524-8c6d-dbbed6ddca04
  serviceAccountName: apb-4a477dee-ee0d-4524-8c6d-dbbed6ddca04
  terminationGracePeriodSeconds: 30
  volumes:
  - name: apb-4a477dee-ee0d-4524-8c6d-dbbed6ddca04-token-676hm
    secret:
      defaultMode: 420
      secretName: apb-4a477dee-ee0d-4524-8c6d-dbbed6ddca04-token-676hm
status:
  phase: Pending
  qosClass: BestEffort

**Comment by johnkim76** [comment]
@jwmatthews @eriknelson @rthallisey I just reset everything, and I can NOT reproduce this either.

**Comment by johnkim76** [comment]
cannot reproduce.. closing.
