### ISSUE TITLE
PodPreset name has a requirement of being less than 63 chars

### ISSUE THREAD

**Issue by jwmatthews** [openshift/ansible-service-broker#283]
The APB name we generate is used to note the PodPreset/Binding/Secret being created by Service Catalog.

There is a problem running from ansibleplaybookbundle and doing a provision/bind of mediawiki and postgres.

When we do the binding and trigger the 2nd deployment of mediawiki it fails to come up.

The below error is present:

(combined from similar events): Error creating: Pod "mediawiki123-2-shk6c" is invalid: metadata.annotations: Invalid value: "podpreset.admission.kubernetes.io/dockerhub-ansibleplaybookbundle-rhscl-postgresql-apb-3xcwz-2v5r4": name part must be no more than 63 characters

**Comment by jwmatthews** [comment]
For a short term workaround I am attempting to specify the "REGISTRY_NAME" to the template as "dh" instead of "dockerhub" to save a few characters.

**Comment by shawn-hurley** [comment]
I have filed a bug with the service catalog
https://github.com/kubernetes-incubator/service-catalog/issues/1047

**Comment by shawn-hurley** [comment]
@jwmatthews I think that we should close this, as kubernetes-incubator/service-catalog#1047 has been closed because they are no longer using pod presets.
