### ISSUE TITLE
Remove organization from the image field in the apb.yml

### ISSUE THREAD

**Issue by cfchase** [openshift/ansible-service-broker#288]
Current behavior:
#apb.yml
image: ansibleplaybookbundle/my-apb
This means that the broker downloads the spec from an organization, but may actually download the image from an entirely different organization, leading to confusion.

Proposed:
#apb.yml
image: my-apb
ASB will assume the apb image is in the same repository and org where the spec was found.

Will require changes in:
* ansible-service-broker - no longer use the org in a spec and use where it's hosted instead.
* ansible-playbook-bundle - remove org from apb-init and build

Reasoning:
1. Stable - Allow a user to download an image, retag it, and then push it to a different org for either testing or production use without modifying and rebuilding.  We want to test the built image as is without modifying it and introducing changes.
2. Less confusion - since a user may forget to change the org, they'd be testing the original image on a different org and may be confused why changes aren't reflected.
3. Reusable - we would want users and developers to be sharing images without forcing them to rebuild the image with changes before pushing to their own organization for use.

**Comment by jwmatthews** [comment]
https://trello.com/c/fIFsrFrf

**Comment by cfchase** [comment]
https://github.com/fusor/apb-examples/issues/81
https://github.com/fusor/ansible-playbook-bundle/issues/69
