### ISSUE TITLE
Broker can't easily deploy alternative APB tags

### ISSUE THREAD

**Issue by eriknelson** [openshift/ansible-service-broker#318]
Some background: today, we merged a major breaking change to the apb.yml schema (multi-plan support). It was a case where the apb.yml schema had changed, and the broker needed an overhaul to support it. This meant that brokers prior to the merge were not able to deploy APBs that were older than the `apb-examples` PR, and vice versa. This was a bit of a special case, because we had previously been faking out a core piece of the OSB spec (plans), but I suspect it will remain a problem going forwards. If we ever make breaking, required changes to apb.yml contents, we're going to end up in the same situation.

This kicked in CI, which rebuilt canary APBs, but latest was not rebuilt. This meant I needed to test against canary APBs, but right now, there is no easy way to configure a broker to deploy from a particular tag.

This is definitely related to #288. The APBs shouldn't care at all about where they live; it breaks portability.

Scope for this issue is, we should determine what belongs in an apb.yml schema, and what should be configurable in the broker so allow for ease of deploying APBs from alternative locations.

**Comment by jmrodri** [comment]
@eriknelson Does PR #357 fix this?

**Comment by eriknelson** [comment]
@jmrodri yes I think that satisfies my original issue.
