### ISSUE TITLE
CONTRIBUTING.md additions

### ISSUE THREAD

**Issue by eriknelson** [openshift/ansible-service-broker#319]
* We should require 2 people with merge access to ACK a PR. One reviewer can easily miss something, a second sanity check gives me a lot of confidence
* Above means we need to enumerate who those people are, either in the contributing doc or somewhere else. I noticed in origin they have "owners" files. A top level doc for us would probably suffice
* Should have a section encouraging new tests for new work, and explicitly state PRs that fail `make test` will not be reviewed until they are passing
* We should have a single script that runs all the preliminary source checks so that contributors can make sure their source is compliant and will pass that part of travis (without running regression stuff). Thinking `vet, lint, format`
* Could add a new makefile target, something like `make check` that runs tests and the source stuff. Add this to the contributing template to say: "Have you verified you pass `make check`?"
* Should talk about [DO NOT MERGE] [WIP] PRs. Please tag them as such to make sure they aren't reviewed and merged.

**Comment by jmrodri** [comment]
The 2 people is good for most of the PRs. But there are some that are really trivial, i.e. docs prs etc. Sometimes a judgement call can be made and just merge it.

**Comment by jmrodri** [comment]
When I updated the .travis.sh I thought about moving the lint etc into the Makefile. I'd prefer that.

**Comment by jmrodri** [comment]
I prefer [WIP] it's shorter. I see them and review them but will never merge one.

**Comment by shawn-hurley** [comment]
:+1: to the ```make check``` target

I also prefer [WIP] for the do not merge tag.

**Comment by djzager** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Documentation Updates](https://trello.com/c/LIxva4xo/434-documentation-updates)

**Comment by djzager** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(0.5) Update Contributing.md Guide to Cover Proposed Workflow for Upstream Branching Policy](https://trello.com/c/NQrZfxKm/314-05-update-contributingmd-guide-to-cover-proposed-workflow-for-upstream-branching-policy)
