### ISSUE TITLE
use 'insecure' parameter

### ISSUE THREAD

**Issue by DarrenRatcliffe** [openshift/ansible-service-broker#333]
can someone please tell me how I can incorporate a parameter within the deployment template that will disable TLS and enable an insecure http route?

**Comment by rthallisey** [comment]
@DarrenRatcliffe you can build your broker image with ```asbd -c $BROKER_CONFIG --insecure```.

 https://github.com/openshift/ansible-service-broker/blob/master/build/entrypoint.sh#L20

**Comment by shawn-hurley** [comment]
@DarrenRatcliffe 

If you are asking about changing the [deployment template](https://github.com/openshift/ansible-service-broker/blob/master/templates/deploy-ansible-service-broker.template.yaml), then I think the solution is to add to the deployment config under the route to include:

```yaml
tls:
  ....
  insecureEdgeTerminationPolicy: Allow 
```

This should allow you to hit the route without using https and have the router continue to the broker.
For that to completely work you will need to have the broker running as @rthallisey has described. 

I could also see us needing this in future so we may want to add as a configuration variable and have the default be ```None```

**Comment by DarrenRatcliffe** [comment]
@rthallisey & @shawn-hurley thanks for the advise, do you have anything a bit more verbose with regards to how to build the new broker image (sorry I am not overly familiar with this aspect)

**Comment by shawn-hurley** [comment]
Hi @DarrenRatcliffe 

```make build-image ORG=<whatever prefix you would prefer````
this will build a docker image called ```<ORG>/ansible-service-broker```

You can then use that image in [catasb](https://github.com/fusor/catasb) by setting up config/my_vars.yml to point to your new broker image and template.

Example:
```yaml
broker_image_name: docker.io/shurley/ansible-service-broker
asb_template_url: file:///<path to file>deploy-ansible-service-broker.template.yaml
```
