### ISSUE TITLE
Unable to start additional hello-world APB in separate project after hello-world APB has been started and bound to DB in same cluster

### ISSUE THREAD

**Issue by djwhatle** [openshift/ansible-service-broker#338]
> ### Bug: Unable to start additional hello-world APB in separate project after hello-world APB has been started and bound to DB in same cluster

**What happened**:
```
1. Start with fresh catasb environment
```
_Perform the following actions in "Project 1"_

```
2. Deploy MySQL APB
3. Deploy hello-world APB
4. Bind hello-world APB to MySQL APB
```

_Perform the following actions in "Project 2"_

```
5. Deploy MySQL APB
6. Deploy hello-world APB
7. APB will fail to start hello-world application pod, trying to mount bind secret from "Project 1"
```

After a bind action has occurred in the cluster involving the hello-world APB, future attempts at launching hello-world APBs in the cluster will attempt to mount the secret from  "Project 1" despite the fact that a bind operation hasn't yet been performed in "Project 2".
 
The second hello-world application pod will attempt to mount a secret outside of its project namespace and will fail to start.

**What you expected to happen**:
Expect to be able to deploy a hello-world APB multiple times in the same OpenShift cluster and have it bind to databases in different projects without cross-project interference. 

**Workaround**
I've been able to avoid this issue by deleting all previous hello-world APB bindings before creating a new one.

**Comment by shawn-hurley** [comment]
I can not reproduce this error,  please re-open if it is still happening.
