### ISSUE TITLE
Reintroduce Broker-API header restriction when k8s issue is settled

### ISSUE THREAD

**Issue by eriknelson** [openshift/ansible-service-broker#34]
Header API versioning should be turned back on when k8s incubator issue is settled. Router was previously restricted to:

```
root := h.router.Headers("X-Broker-API-Version", "2.9").Subrouter()
```

**Comment by eriknelson** [comment]
https://github.com/fusor/ansible-service-broker/pull/35

**Comment by rthallisey** [comment]
@eriknelson is this still relevant? How can we close this?

**Comment by eriknelson** [comment]
@rthallisey Posted a PR (removes the comment). It's still relevant, but I'm of the opinion we should close this.
