### ISSUE TITLE
Current parameter format in apb.yml doesn't allow merging of shared and plan-unique params

### ISSUE THREAD

**Issue by djwhatle** [openshift/ansible-service-broker#347]
## Bug: Current parameter format in apb.yml doesn't allow merging of shared and plan-unique params

**What happened**:

- Was writing a multi-plan APB with high number of parameters (~30 params, 200 lines of code)
- Wanted to share most parameters while making ~5 parameters unique to each plan
- Tried merging "shared" and "unique" parameter variables using YAML's anchor/alias feature

```
shared_params: &shared_params
  - name: aws_access_key
    ...
  - name: aws_secret_key
    ...

plan_1_params: &plan_1_params
  - name: unique_param_X
    ...

plan_2_params: &plan_1_params
  - name: unique_param_Y
    ...

plans:
  - name: plan-1
    parameters:
      << : *shared_params
      << : *plan_1_params
    ...

  - name: plan-2
    parameters:
      << : *shared_params
      << : *plan_2_params
    ...

```
- This approach doesn't work, service-catalog ends up showing no parameters for APB
- This is a limitation of YAML (YAML is only capable of merging mappings, not lists)
- Can be worked around in the service broker to provide a better APB authoring experience

**What you expected to happen**:

- Parameters merge as expected
- Able to write write an APB complying with DRY
- Able to avoid multiplier on APB line count every time new plan is added

**Proposed Fix**:

- Change ansible-service-broker to accept a different format in apb.yml which will allow param merging
- Update all existing apb-examples to use this new format

```
shared_params: &shared_params
  aws_access_key:
    type: string
    required: true
    ...
  aws_secret_key:
    type: string
    required: true
    ...

plan_1_params: &plan_1_params
  unique_param_X:
    type: string
    required: true
  ...

plan_2_params: &plan_1_params
  unique_param_Y:
    type: string
    required: true
  ...

plans:
  - name: plan-1
    parameters: # map[string]PD
      << : *shared_params
      << : *plan_1_params
    ...

  - name: plan-2
    parameters: # map[string]PD
      << : *shared_params
      << : *plan_2_params
    ...
```

**Comment by jmrodri** [comment]
I still prefer the original format with the list of objects
```
  - name: aws_access_key
    ...
  - name: aws_secret_key
    ...
```

We need to figure out a better way to solve the inheritance if yaml itself doesn't support it natively.

**Comment by jmrodri** [comment]
The short term work around is to duplicate the keys until we solve this permanently.

**Comment by jmrodri** [comment]
Closing since this is unlikely to ever get fixed.
