### ISSUE TITLE
Unable to deploy an APB with privileged security context

### ISSUE THREAD

**Issue by dymurray** [openshift/ansible-service-broker#351]
> # Feature:
Ability to specify if an APB needs privileged security permissions as opposed to 'restricted' by default
> # Bug:
I am unable to provision an APB which accesses files in /root/ on the container

**How to reproduce it**:
Create an APB and reference a container in the deployment config which requires root access to run the startup binary.

**Comment by dymurray** [comment]
Initial thoughts are that an APB would specify in their spec whether or not privileged access is needed.

**Comment by jwmatthews** [comment]
Note that work on refreshing the ManageIQ APB is waiting on this feature.
Trello card:  https://trello.com/c/sxfZlTYm

**Comment by rthallisey** [comment]
@dymurray has anything changed on this? Can apbs access /root?

**Comment by dymurray** [comment]
Nothing has changed with this, still a valid issue. APBs can still not be deployed with a `privileged` scc.

**Comment by mhrivnak** [comment]
Could you expand on the use case for this? Why does an APB need to access files in /root/ ? Could the APB's Dockerfile make those files available elsewhere?

**Comment by dymurray** [comment]
@mhrivnak The intention is more that the APB can declare if it needs elevated permisisons up front so that it is launched in the proper context. I'm unsure if /root/ is a good usecase. It's more about consuming images that weren't meant to be run in the `restricted` scc.
