### ISSUE TITLE
Fix auto container rebuilds

### ISSUE THREAD

**Issue by eriknelson** [openshift/ansible-service-broker#36]
Since ansibleapp assets got moved back to this repo, automated builds and pushes for relevant containers are broken. Needs to get fixed.

**Comment by eriknelson** [comment]
Related: https://github.com/fusor/ansibleapp-library/issues/37

**Comment by rthallisey** [comment]
https://github.com/openshift/ansible-service-broker/pull/240

**Comment by rthallisey** [comment]
Proposed work
-----
- ~~Automated builds for source~~
  - #240
- Automated builds for binary

**Comment by eriknelson** [comment]
Fixed with jenkins/dockerhub builds.
