### ISSUE TITLE
Auto bootstrap is clearing apb-push sourced specs

### ISSUE THREAD

**Issue by eriknelson** [openshift/ansible-service-broker#391]
**What happened**:
APB developer with no existing APB's in their Dockerhub org wrote up a test APB, ran apb push, and the broker loaded it into it's `/spec` correctly. After waiting 5min, service still did not show up. Auto-bootstrap kicked in and cleared **all** specs from `/spec`, so it destroyed the one sourced from `apb-push`.
 
Log: [broker.txt](https://github.com/openshift/ansible-service-broker/files/1246547/broker.txt)

**What you expected to happen**:
Auto bootstrap should not be clearing apb-push sourced specs.

Longer term, we should be able to enable/disable, and configure auto-bootstrap on a registry basis. It should be disabled for the apb-push type registry adapter by default.

**Comment by eriknelson** [comment]
Related #49

**Comment by jmrodri** [comment]
Do we disable auto bootstrap in dev mode?

**Comment by dymurray** [comment]
Working on a PR for this, associated bug is here: https://bugzilla.redhat.com/show_bug.cgi?id=1498933

**Comment by dymurray** [comment]
https://github.com/openshift/ansible-service-broker/pull/477
