### ISSUE TITLE
Possibility to run the apb pod at the different namespace than the target namespace

### ISSUE THREAD

**Issue by rbo** [openshift/ansible-service-broker#408]
**This form is for bug reports and feature requests. Major features will go through a [spec process](https://github.com/openshift/ansible-service-broker/blob/master/CONTRIBUTING.md).**

> # Feature:

Possibility to run the apb pod at the different namespace than the target namespace. 
**For example/use case:**

Developer ordered a service called "oracle database" for the namespace "my-cool-app".
Apd pod for "oracle database" provisioning start at namespace  "my-cool-app" and provide the service "oracle database".

For the provisioning of the "oracle database" service it is necessary to have some secret credentials in the pod. I want to hide & protect those information and the pod from the Developer. And for me is the perfect solution is to run the apb pod at a different namespace.
The apb pods creates only the service and connection credentials at namespace "my-cool-app"

If I have seen this correctly, at one of the first alpha releases the apd pod run at the different namespace. 

**What happened**:

Developer ordered a service called "oracle database" for the namespace "my-cool-app".
Apd pod for "oracle database" provisioning start at namespace  "my-cool-app" and provide the service "oracle database".

**What you expected to happen**:

Developer ordered a service called "oracle database" for the namespace "my-cool-app".
Apd pod for "oracle database" provisioning start at namespace  "my-secret-apb" and provide the service "oracle database".

**How to reproduce it**:

**Comment by jwmatthews** [comment]
@rbo thank you for the issue, this sounds like a use case will will want to support.

**Comment by shawn-hurley** [comment]
@jwmatthews I believe this is closed by #428. Should we close this issue?

**Comment by shawn-hurley** [comment]
This was closed because the APB is being launched in a new namespace now. If this is not the desired behavior please re-open.
