### ISSUE TITLE
Some APB templates missing in catalog

### ISSUE THREAD

**Issue by shortsteps** [openshift/ansible-service-broker#415]
Executing your latest run_latest_build.sh (downloaded from master today), I guess some APB templates are missing in the catalog. For example the MediaWiki and PostgreSQL APB you mention in README. I only have 4 new items.

In `oc logs asb-1-ktv17 -c asb` in can see some errors:

> [2017-09-01T14:39:50.057Z] [DEBUG] Registry::imageToSpec
> [2017-09-01T14:39:50.192Z] [ERROR] V1 Schema Manifest does not exist in registry

Is that a DockerHub issue?
Thanks a lot

**Comment by shortsteps** [comment]
My fault, I'm closing the issue.
Waiting other ten minutes or less the catalog has been populated correctly.

Sorry, and hope it can help someone else to be more patient ;)

**Comment by eriknelson** [comment]
@shortsteps This is actually a known issue -- I'm working with the service catalog folks to make the polling interval configurable and to also expose a manual trigger. Hopefully we'll have that soon :)
