### ISSUE TITLE
spec.authInfo.basicAuthSecret: Required value: a basic auth secret is required

### ISSUE THREAD

**Issue by slaskawi** [openshift/ansible-service-broker#443]
**What happened**:

When I ran `run_latest_build.sh` script on my local dev environment (Fedora F25), the output contained this error:

```
The Broker "ansible-service-broker" is invalid: spec.authInfo.basicAuthSecret: Required value: a basic auth secret is required
```

As a result, none of the APBs were present in the Service Catalog.

**How to reproduce it**:

Just run `run_latest_build.sh` and observe the output.

**Comment by slaskawi** [comment]
I managed to fix it locally by removing https://github.com/openshift/ansible-service-broker/blob/master/templates/deploy-ansible-service-broker.template.yaml#L210. But I guess this is not proper solution...

**Comment by slaskawi** [comment]
@jmontleon Any update?

**Comment by jmontleon** [comment]
Can you let me know if you've made any changes to the run_latest_build.sh script. I am not able to reproduce this error when running it.

**Comment by slaskawi** [comment]
@jmontleon interesting... let me try it...

**Comment by jmontleon** [comment]
There were some updates to the template and possibly the run scripts in the last several hours for bearer token auth. It's possible a side effect of one of these was to fix or mask the issue you were seeing. If not we can continue to try and track it down.

**Comment by slaskawi** [comment]
It must have been that! I can not reproduce it any longer. Thank you @jmontleon!
