### ISSUE TITLE
Broker is unable to load APBs from private Dockerhub repos

### ISSUE THREAD

**Issue by djwhatle** [openshift/ansible-service-broker#448]
> # Bug: Broker is unable to load APBs from private Dockerhub repos

**What happened**:
 - Make one of my APB image repos private
 - Set up catasb with my Dockerhub org
 - Using valid Dockerhub credentials that have access to my private repo
 - APB doesn't show up in catalog on Web UI
 - Error message shows up in asb pod logs

```
  ...
  | [2017-09-22T14:49:26.341Z] [DEBUG] Trying to load djwhatle/s3-apb
  | [2017-09-22T14:49:26.341Z] [DEBUG] Filter applied against registry: dh
  | [2017-09-22T14:49:26.341Z] [DEBUG] APBs passing white/blacklist filter:
  ...
  | [2017-09-22T14:49:26.341Z] [DEBUG] -> djwhatle/s3-apb
  ...
  | [2017-09-22T14:49:26.434Z] [DEBUG] Registry::imageToSpec
  | [2017-09-22T14:49:26.535Z] [ERROR] V1 Schema Manifest does not exist in registry
  ...

```

**What you expected to happen**:
 - APB from private Dockerhub repo shows up as long as my credentials have access
 - Error message in broker logs directly tells me that auth failed trying to get a particular repo

**How to reproduce it**:
 - Make a an APB repo private in your catasb Dockerhub org
 - It shouldn't show up in the Service Catalog

**Comment by djwhatle** [comment]
Have tested a fix for this issue https://github.com/openshift/ansible-service-broker/pull/449.

Waiting on fix PR to pass CI and then we can provide a broker image containing the fix.

**Comment by shawn-hurley** [comment]
@djwhatle is this fixed after the merge? Can you reopen this issue if it is still a problem?

**Comment by djwhatle** [comment]
Haven't tested again after you merged, but it worked when it was a PR.
