### ISSUE TITLE
Expose user/cluster information to APBs, example so created objects can be tagged with a label of user requesting.

### ISSUE THREAD

**Issue by jwmatthews** [openshift/ansible-service-broker#470]
# Feature

When running an APB it would be helpful if information such as below was available for the APB to obtain and process.  
 - User
 - Service ID
 - Namespace

For example, creating an APB for provisioning a remote resource on a cloud provider.  It would be useful if the APB could annotate the created resources with some information about where the request came from such as: cluster_url, requesting_user, namespace, related service id

**Comment by rthallisey** [comment]
Related to https://github.com/openshift/ansible-service-broker/issues/470 . We could use the [kubernetes downward API](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/) to gather some of this information and re post it as an annotation. @maleck13 is working on a module that is doing something similar https://github.com/ansibleplaybookbundle/ansible-asb-modules/pull/9 .

**Comment by shawn-hurley** [comment]
I think that we may also want to see if whatever mechanism we decide on can also be used to pass along the proxy configs we may want to consider that as well?

**Comment by djzager** [comment]
Just to add some color, what values are given to an APB:

```
$ oc logs -n localregistry-mediawiki-apb-prov-7zxb5 apb-6dd23918-9225-4bd0-ad34-75bc5d15fb31
+ [[ provision --extra-vars {
"_apb_plan_id":"default",
"_apb_service_class_id":"c23ec213bb8dea1577230c5ce005b9c2",
"_apb_service_instance_id":"54636ad3-0378-49a1-a494-f97d0a0daf8e",
"cluster":"openshift",
"mediawiki_admin_pass":"pass",
"mediawiki_admin_user":"admin",
"mediawiki_db_schema":"mediawiki",
"mediawiki_site_lang":"en",
"mediawiki_site_name":"MediaWiki",
"namespace":"bazproject"} == *\s\2\i\/\a\s\s\e\m\b\l\e* ]]
+ ACTION=provision
```

Could also look at https://github.com/openshift/ansible-service-broker/blob/master/docs/service-bundle.md

**Comment by jmrodri** [comment]
I think we have enough information being exposed right now. No new requests have come in recently. Closing this as DONE!
