### ISSUE TITLE
Last Operation description

### ISSUE THREAD

**Issue by maleck13** [openshift/ansible-service-broker#475]
**This form is for bug reports and feature requests. Major features will go through a [spec process](https://github.com/openshift/ansible-service-broker/blob/master/CONTRIBUTING.md).**

> # Feature:

It would be nice for long running apbs, if a description could somehow be provided via apb about what the apb was doing to the user, both to inform and indicate progress. The service broker api supports a last_operation, which I see is in place, however the description appears to always be empty.
Wondering if there are any thoughts on how this might be achieved and if it is someting the asb wants to support

**Comment by rthallisey** [comment]
https://github.com/openshift/ansible-service-broker/pull/505

**Comment by maleck13** [comment]
@rthallisey is this actually solved by the PR? Or is it something not wanted? Looking at the PR the description is still empty.

**Comment by rthallisey** [comment]
@maleck13 Ok I thought that PR covered it. Reopening.

**Comment by maleck13** [comment]
On this particular feature, would a proposal be welcome?
An option I was considering:
- Writing the description of the last operation to a known location and have it collected by the broker periodically, I believe something similar happens for collecting the credentials for the secret. An example of this description would perhaps be:
```progress 60%: creating initial realm and clients```

**Comment by rthallisey** [comment]
@maleck13 Proposals are always welcome!! 👍 

> Writing the description of the last operation to a known location and have it collected by the broker
> periodically, I believe something similar happens for collecting the credentials for the secret. An
> example of this description would perhaps be:
> ```progress 60%: creating initial realm and clients```
>
Looks good to me 👍.  On the apb side, we could have a simple module handle putting the description in place for the broker to find.  With bind, we exec into the pod.  So like you said, we can use the same workflow.
