### ISSUE TITLE
Deleting 1 APB service instance triggers 4 deprovision pods inside of 4 temporary namespaces

### ISSUE THREAD

**Issue by djwhatle** [openshift/ansible-service-broker#483]
> ### Bug: Deleting 1 APB service instance triggers 4 deprovision pods inside of 4 temporary namespaces

Bugzilla Link - [Bug 1500930](https://bugzilla.redhat.com/show_bug.cgi?id=1500930)

## Description

After successfully provisioning an SNS APB, I clicked "Delete" on the SNS APB service instance from the OpenShift Web UI and noticed that 4 temporary namespaces had been created, each containing an SNS APB deprovision pod. 

In my testing, deleting a service instance always resulted in exactly 4 deprovision pods being spawned.

If you look closely at the logs below, you'll notice that ASB receives 4 separate "delete" calls from the service-catalog, all with the same "service_id". Instead of acting upon one call and disregarding the rest, all calls are acted upon.

`
172.17.0.5 - - [11/Oct/2017:18:25:16 +0000] "DELETE /ansible-service-broker/v2/service_instances/9b5908cf-dcd3-405d-87fc-3ae63bbe5e5d?accepts_incomplete=true&plan_id=topicwithsub&service_id=ab883cebb0a87311150230384078477c HTTP/1.1" 200 58
`

(See BZ for additional info, logs)

**Comment by eriknelson** [comment]
Closed by #488
