### ISSUE TITLE
run_latest_build.sh needs SVC_CAT_API_VER="servicecatalog.k8s.io/v1alpha1" for "oc cluster up" on origin v3.6.0

### ISSUE THREAD

**Issue by ArminMW** [openshift/ansible-service-broker#509]
`run_latest_build.sh` failed to deploy the Ansible Service Broker on my fresh installed OpenShift Origin v3.6.0 `oc cluster` with the following error message:

`Error from server (BadRequest): Broker in version "v1beta1" cannot be handled as a Broker: no kind "Broker" is registered for version "servicecatalog.k8s.io/v1beta1"`

After some analysis and some try'n'error I added this variable to the `run_latest_build.sh` script:

`SVC_CAT_API_VER="servicecatalog.k8s.io/v1alpha1"`

And I modified the `oc process [...] | oc create -f -` to include

`-p SVC_CAT_API_VER="$SVC_CAT_API_VER"`

to successfully deploy the Ansible Service Broker.

Additional info:;

```
$ oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
kubernetes v1.6.1+5115d708d7

$ cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core) 

$ docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-55.gitc4618fb.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      c4618fb/1.12.6
 Built:           Thu Sep 21 22:33:52 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-55.gitc4618fb.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      c4618fb/1.12.6
 Built:           Thu Sep 21 22:33:52 2017
 OS/Arch:         linux/amd64
```

Thus, this now works for me with this workaround. You may close this issue. I just wanted to pass this info upstream.

**Comment by rthallisey** [comment]
@ArminMW thanks for the issue.  I think we're going to create a 3.6 branch shortly that points to the 3.6 release of the service-catalog. So in the future, the releases will match up and this issue will go away when using ```run_latest_build.sh``` out of the box.

**Comment by rthallisey** [comment]
Sorry for the confusion. The [release-0.9](https://github.com/openshift/ansible-service-broker/tree/release-0.9) branch is primarily targeted for 3.6.  The master branch is in progress of defaulting to 3.7 for the upcoming release.  If you want to use master with 3.6, it's possible, but you may run into some issues.
