### ISSUE TITLE
Add the action that created the pod as a label and as part of the name

### ISSUE THREAD

**Issue by maleck13** [openshift/ansible-service-broker#512]
> # Feature:

When performing a service catalog action such as provision unprovision bind etc, a pod is started to perform this action.
The pod is named something like:
```  apb-6e83df98-a588-452d-939a-c07a850b1b5c ```

I think it would be useful to be able to see at a glance what the pod was doing. 

I would suggest adding the following enhancements:

1) add the name of the action to the pod ``` apb-6e83df98-a588-452d-939a-c07a850b1b5c-bind```
2) add a label to allow simple querying from the API ```apb-action:bind```

If this is something that seems reasonable, I am also happy to take on the work

**Comment by rthallisey** [comment]
@maleck13 thank you for the suggestion.  I think adding the action to the end of the pod name would be a nice addition for debugging 👍. 

> 2. add a label to allow simple querying from the API apb-action:bind
>
Can you explain more about this addition? What does the query look like? What useful information do you expect back from it?

**Comment by djzager** [comment]
@maleck13 As the broker is written currently, the transient namespaces follow the pattern `${apb-fqname}-${apb-action}-${unique-suffix}` and the labels added to both the pods + namespaces are the `apb-fqname` and `apb-action`. Example below (with broker configured to keep the transient namespaces). Is there more that we should be doing?

```
$ oc get namespaces
NAME                                STATUS    AGE
ansible-service-broker              Active    4m
default                             Active    5m
dh-hello-world-apb-prov-jqvvv       Active    5s
fooproject                          Active    5s
kube-public                         Active    5m
kube-service-catalog                Active    5m
kube-system                         Active    5m
myproject                           Active    5m
openshift                           Active    5m
openshift-infra                     Active    5m
openshift-node                      Active    5m
openshift-template-service-broker   Active    5m

$ oc get pods -n dh-hello-world-apb-prov-jqvvv -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/scc: restricted
    creationTimestamp: 2017-10-31T14:13:20Z
    labels:
      apb-action: provision
      apb-fqname: dh-hello-world-apb
    name: apb-aec44a61-1495-4b4f-9eae-5500af755c5b
    namespace: dh-hello-world-apb-prov-jqvvv
    resourceVersion: "2247"
    selfLink: /api/v1/namespaces/dh-hello-world-apb-prov-jqvvv/pods/apb-aec44a61-1495-4b4f-9eae-5500af755c5b
    uid: a5db0523-be45-11e7-8e5b-64006a6fb904
```

**Comment by maleck13** [comment]
@djzager No I think this issue can be closed now. I was on an older version of the asb previously when thinking about this. At the time the pods were being created in the same ns and didn't have the action.

**Comment by djzager** [comment]
Thank you for filing the issue @maleck13. I'm also glad that it's already taken care of :sunglasses:
