### ISSUE TITLE
Proposal: using interfaces for DAO operations to allow simple unit tests

### ISSUE THREAD

**Issue by maleck13** [openshift/ansible-service-broker#542]
> # Feature:
When looking at how I would implement the last_operation description https://github.com/openshift/ansible-service-broker/pull/537
I wondered how I would go about adding tests for it also. I know there are a number of end to end tests that are used, but wondered what appetite there was to improving the ability to add unit tests?

If we were to use interfaces to pick out the relevant parts of the DAO object, I think it would give a good starting place.

I have created a reference PR to show what I mean and am interested in thoughts and feedback.

**Comment by jmrodri** [comment]
I started trying to get coverage report in a branch so that we could see how bad the gap was in our testing. Mocking is something we want to do, the dao, and `RunCommand` are 2 big ones that are holding a lot of this back.

**Comment by rthallisey** [comment]
@maleck13 did code from #543 make it into any of your PR? I don't want to lose out on all those changes to broker_test.go.

**Comment by maleck13** [comment]
The changes to broker_test are not in the PRs but the concepts are there. There is an interface around the DAO actions for the Jobs for instance. Which I think can form the basis for future changes to how testing and dependency injection is approached.
I was worried about the PR getting stale as so many changes are happening

**Comment by rthallisey** [comment]
Ok. We can circle back to this after #619 is merged
