### ISSUE TITLE
installer is broken

### ISSUE THREAD

**Issue by karmab** [openshift/ansible-service-broker#566]
**This form is for bug reports and feature requests. Major features will go through a [spec process](https://github.com/openshift/ansible-service-broker/blob/master/CONTRIBUTING.md).**

> # Bug:

**What happened**:
deployment hangs on the Run "oc cluster up to start the cluster" task

**What you expected to happen**:
ansible service broker is deployed

**How to reproduce it**:
launch the deployment script with either latest or v3.7.0-rc
the following task beeing executed failed

/root/bin/oc cluster up --routing-suffix=172.17.0.1.nip.io --public-hostname=192.168.122.24 --host-pv-dir=/persistedvolumes --image=docker.io/openshift/origin --version=latest  --service-catalog=true

**Comment by karmab** [comment]
[origin_logs.txt](https://github.com/openshift/ansible-service-broker/files/1490942/origin_logs.txt)

**Comment by rthallisey** [comment]
@karmab what OS are you running?  This looks like an issue folks are seeing when running Fedora 27: https://github.com/openshift/origin/issues/15038 . Work around is ```rm -rf /usr/share/rhel/secrets```.

**Comment by karmab** [comment]
suggested workaround did the trick for me
