### ISSUE TITLE
Getting started guide doesn't work on macOS

### ISSUE THREAD

**Issue by aliok** [openshift/ansible-service-broker#588]
> # Bug:

**What happened**:
I tried the "Getting Started with the Ansible Service Broker" document here on my Mac: 
https://github.com/openshift/ansible-service-broker#getting-started-with-the-ansible-service-broker

**What you expected to happen**:
Being able to start a local OpenShift cluster with ASB enabled.

**How to reproduce it**:
Try this on a Mac:
```
wget https://raw.githubusercontent.com/openshift/ansible-service-broker/master/scripts/run_latest_build.sh
chmod +x run_latest_build.sh
./run_latest_build.sh
```

#### More details:

* Command `ip` doesn't exist on a Mac: https://github.com/openshift/ansible-service-broker/blob/master/scripts/run_latest_build.sh#L36
I modified the file manually to solve this problem.

**Comment by rthallisey** [comment]
@aliok can you provide the command you used on mac?

**Comment by rthallisey** [comment]
@jwmatthews or @shawn-hurley can either of you try this on you mac and update the docs if there's an issue?
