### ISSUE TITLE
We should move to using the openshift client-go

### ISSUE THREAD

**Issue by shawn-hurley** [openshift/ansible-service-broker#590]
# Feature: Use Openshift Client Go and Openshift API

The [openshift client-go] and [api] should be used instead of our [openshift client] that we have been using. This will require a change to our copied modules [here]() as well, but should then easily changed. 

This will give us access to all of the openshift APIs without building our own rest clients now.

**Comment by jmrodri** [comment]
Fixed by PR https://github.com/automationbroker/bundle-lib/pull/105
