### ISSUE TITLE
Type fields in APB specs are case-sensitive

### ISSUE THREAD

**Issue by eriknelson** [openshift/ansible-service-broker#592]
`apb push -o` an APB spec with a type of `String` rather than `string` will cause the catalog endpoint to return empty spec objects, since they end up erroring on this case statement. Of potential importance, this is the local openshift adapter:

https://github.com/openshift/ansible-service-broker/blob/master/pkg/broker/util.go#L200

This causes `apb list` to display an empty entry (it will look like a blank line).

Interestingly, an additional bootstrap will resolve the problem...somehow. `apb bootstrap && apb list` will display the expected entry, so something must be lowercasing the type.

**Comment by shawn-hurley** [comment]
Looks like this is causing the same behaviour as this https://github.com/openshift/ansible-service-broker/issues/388 

I assume we should just cast the switch to lower case.

**Comment by eriknelson** [comment]
@shawn-hurley yep, was thinking the same thing.

**Comment by mhrivnak** [comment]
I'll submit a fix for this.
