### ISSUE TITLE
JobMsg is too generic, needs to have the binding uuid

### ISSUE THREAD

**Issue by jmrodri** [openshift/ansible-service-broker#631]
While implementing the binding job, I found that I need to also pass the binding uuid instead of the instanceuuuid in the JobMsg. We used to have specific WorkMsgs which would've made this easier with a new BindingMsg.

Probably not work creating a bunch of msgs, need to enhance JobMsg to allow for additional data.

**Comment by jmrodri** [comment]
For the async binding work, I just added the BindingUUID to the JobMsg. Probably need a better mechanism for it.

**Comment by jmrodri** [comment]
@jianzhangbjz no QE required for this task except for regression testing.

**Comment by jianzhangbjz** [comment]
@jmrodri Thanks for your reminder, I clear, I just want to track its progress. :)

**Comment by jmrodri** [comment]
This is no longer an issue for me. Fixed current release.
