### ISSUE TITLE
Revisit GetServiceInstance and GetBind return objects in broker.

### ISSUE THREAD

**Issue by jmrodri** [openshift/ansible-service-broker#632]
GetServiceInstance in broker.go returns a ServiceInstance. GetBind returns a BindResponse. Most of the broker methods return a *Response. Maybe we should add a GetServiceInstanceResponse method to the broker and have the handler call that. Keep GetServiceInstance simply as util method.

**Comment by jmrodri** [comment]
@jianzhangbjz no QE required for this issue. It's purely a developer task.

**Comment by jianzhangbjz** [comment]
@jmrodri Thanks! I clear, I just want to track the related code and its progress. :)

**Comment by jmrodri** [comment]
Closing, we can refactor if we want, but not really a bug.
