### ISSUE TITLE
run_latest_build.sh should support Mac OS X/minishift

### ISSUE THREAD

**Issue by cunningt** [openshift/ansible-service-broker#639]
First line of run_latest_build.sh is:
DOCKER_IP="$(ip addr show docker0 | grep -Po 'inet \K[\d.]+')"

I don't believe that the ip executable is available on Mac OS X, but if "minishift ip" is substituted here for the entire statement, I believe it returns the correct address needed here.

tcunning@tcunning-OSX:/tmp$ ORIGIN_VERSION=v3.7.0 ./run_latest_build.sh
./run_latest_build.sh: line 36: ip: command not found
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
Starting OpenShift using docker.io/openshift/origin:v3.7.0 ...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK

**Comment by shawn-hurley** [comment]
This script is used to start a new cluster. If you are already using minishift then you should use the [minishift addon](https://github.com/openshift/ansible-service-broker/blob/master/docs/minishift.md) to deploy the broker. On Mac OS X we will default the IP address to `127.0.0.1` and that has bee completed [here](https://github.com/openshift/ansible-service-broker/pull/626) but I will work on a PR to quiet the error output of that line.
