### ISSUE TITLE
ASB support multi registry with the same name currently

### ISSUE THREAD

**Issue by zihantang-rh** [openshift/ansible-service-broker#644]
**This form is for bug reports and feature requests. Major features will go through a [spec process](https://github.com/openshift/ansible-service-broker/blob/master/CONTRIBUTING.md).**

**What happened**:
In v3.7, if config broker-config with multi registry with the same name , the asb pod will fail with errror 
`ERROR: Failed to read config file
registry name must be unique
`
But in v3.9  the asb pod will start successfully. And successfully loaded apbs from the last registry.  
Is it the expected feature ? @jwmatthews 

openshift v3.9.0-0.19.0
kubernetes v1.9.0-beta1
ASB: brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/ose-ansible-service-broker:v3.9 [1.1.4]

**What you expected to happen**:

**How to reproduce it**:
1. Config broker-config with:
  - type: dockerhub
    name: test
    url:  https://registry.hub.docker.com
    org:  ansibleplaybookbundle
    tag:  latest
    white_list: [.*-apb$]
  - type: dockerhub
    name: test
    url:  https://registry.hub.docker.com
    org:  zjianbjz
    tag:  latest
    white_list: [.*-apb$]
2. Restart broker.
Logs:
[2018-01-16T09:19:30.029Z] [DEBUG] - APBs passing white/blacklist filter:
[2018-01-16T09:19:30.029Z] [DEBUG] - -> zjianbjz/fail-apb
[2018-01-16T09:19:30.029Z] [DEBUG] - -> zjianbjz/hello-world-db-apb
[2018-01-16T09:19:30.029Z] [DEBUG] - -> zjianbjz/mediawiki-apb
[2018-01-16T09:19:30.029Z] [DEBUG] - -> zjianbjz/postgresql-apb
[2018-01-16T09:19:30.029Z] [DEBUG] - -> zjianbjz/hello-test-apb
[2018-01-16T09:19:30.117Z] [DEBUG] - Registry::imageToSpec
[2018-01-16T09:19:30.981Z] [NOTICE] - Broker successfully bootstrapped

**Comment by jmrodri** [comment]
This looks

**Comment by jmrodri** [comment]
This looks related to the recent config refactor we did.

**Comment by rthallisey** [comment]
Since the ```org``` field is different, we will likely get a different set of images.  So this is the functionality we want.

**Comment by shawn-hurley** [comment]
@rthallisey I think that is the issue. The FQName only takes into account of the registry name and the name defined from the spec yaml. So dh-mediawiki123-apb, where registry name is dh and apb name is mediawiki123-apb. I think that this is a regression bug and as @jmrodri has mentioned is due to the config refactor.

**Comment by shawn-hurley** [comment]
Create a bugzilla for this issue: 
https://bugzilla.redhat.com/show_bug.cgi?id=1535182

Will keep both open to track this regression.
