### ISSUE TITLE
Better test and validate proxy variable permutations

### ISSUE THREAD

**Issue by eriknelson** [openshift/ansible-service-broker#663]
The `ProxyConfig` is loaded from the broker's environment inside `executor.go`: https://github.com/openshift/ansible-service-broker/blob/master/pkg/apb/executor.go#L152

There were a few scenarios that were less obvious to me:
  * What is the expected behavior if `HTTP_PROXY` or `HTTPS_PROXY` is set, but the other one is not?
  * If `NO_PROXY` is present, but neither proxy is configured...I'm assuming that's useless.
  * What to do if the variables are set, but empty? Treat as if they are not present? Warn?

Should consider a complete matrix, validate it as to whether or not the variables should be passed on to the APB, and then unit test it.

**Comment by eriknelson** [comment]
Relevant PR that introduced the `TODO`: https://github.com/openshift/ansible-service-broker/pull/654

**Comment by eriknelson** [comment]
@mhrivnak curious about your opinion on this one. I'm not a proxy expert by any means.

**Comment by mhrivnak** [comment]
> What is the expected behavior if HTTP_PROXY or HTTPS_PROXY is set, but the other one is not?

I think you'll get exactly the behavior you'd suspect. One type of traffic will use a proxy, and the other not. It's weird, but we can probably contrive a use case or two. Perhaps an organization wants to know what insecure non-TLS/SSL traffic is occurring so they can track it, attempt to secure it, make sure nothing important is being leaked, etc. So they want to run that traffic through a proxy, but they don't care about HTTPS traffic.

> If NO_PROXY is present, but neither proxy is configured...I'm assuming that's useless.

Agreed. No harm, but no benefit either.

> What to do if the variables are set, but empty? Treat as if they are not present? Warn?

Interesting scenario. The most likely reason for setting them to an empty string would be to override pre-existing settings, in a case where you don't have the ability to "unset" the variable by name. So maybe an APB has some proxy environment variables baked into it for some reason, and a user wants to override that at runtime. We don't give them a way to unset the variables, but we do give them a way to clobber their values.

So I would preserve the values and pass them through regardless of content. Although logging about it when the string is empty may be a good idea, just in case it was unintentional.
