### ISSUE TITLE
make serviceInstance details available to the playbook

### ISSUE THREAD

**Issue by jaymccon** [openshift/ansible-service-broker#674]
# Feature:

As an APB developer it is useful to have the details of who provisioned a service. In the context of the AWS service broker this would enable:
* tagging of the AWS resources so that orphaned resources can be detected and cleaned up
* generation of a unique key/idempotency token for resource provisioning
* usage costs can be allocated to an openshift cluster/project

Making (at least) the following values available to the provision and de-provision playbooks at runtime would allow for this:
* OpenShift cluster dns suffix
* username
* namespace
* ServiceInstance id

**Comment by johnkim76** [comment]
@jaymccon the [PR#832](https://github.com/openshift/ansible-service-broker/pull/832) was merged which provides the username information of the last requesting user.  The details of the `_apb_last_requesting_user` parameter is discussed [here](https://github.com/openshift/ansible-service-broker/blob/master/docs/service-bundle.md#last-request-user). 

I'm still working on the `openshift_routing_suffix`

**Comment by jmrodri** [comment]
I'm calling this one done. If we really need the `openshift_routing_suffix` let's open a new issue. Fixed by PR #832
