### ISSUE TITLE
custom error messaging 

### ISSUE THREAD

**Issue by jaymccon** [openshift/ansible-service-broker#675]
# Feature:

Allowing an APB to return custom error messages that gets surfaced by service catalog if a provisioning operation fails will ease troubleshooting and improve customer experience.

**Comment by rthallisey** [comment]
I think this being implemented here https://github.com/openshift/ansible-service-broker/issues/475.  Let me know if this is different than last_operation.

**Comment by shawn-hurley** [comment]
https://github.com/openshift/ansible-service-broker/pull/607 

This is a start of this I think.

**Comment by jwmatthews** [comment]
@jaymccon (Amazon developer on AWS Service Broker) is looking for the Web Console to display a useful error when there is an error running an AWS APB.

Let's say provisioning RDS fails with a CloudFormation error.
The APB needs to grab the correct error message and send back to Broker...then we need the error message to flow up to end user at web-console so they see "RDS APB failed with CloudFormation error blah......", opposed to "Provision Failed".

This issue may involve some investigation beyond just Broker side.

**Comment by maleck13** [comment]
@rthallisey @jwmatthews I think using the last_operation_description module along with the PRs associated with it would solve this as it would allow the developer to set the last_operation description and that then flows through to the catalog and to the web console under the service instance.
Related PRS

**Module** https://github.com/ansibleplaybookbundle/ansible-asb-modules/pull/9**
**Broker** https://github.com/openshift/ansible-service-broker/pull/619

The work is largely in place now will need to rebase the 619 PR

**Comment by eriknelson** [comment]
I would think the `Status` of a `ServiceInstance` is a canonical way to surface that information. Would also expect to find the last_operation.description there.

**Comment by maleck13** [comment]
Yes I believe the last operation is updated on the service instance .

**Comment by rthallisey** [comment]
@jaymccon I think we're going to track this from #619.

> I would think the Status of a ServiceInstance is a canonical way to surface that information. Would also expect to find the last_operation.description there.
>
Here's @maleck13's test case: https://github.com/openshift/ansible-service-broker/pull/619#issuecomment-359875771
