### ISSUE TITLE
Define a firmer error checking policy for registry adapters

### ISSUE THREAD

**Issue by rthallisey** [openshift/ansible-service-broker#684]
# Feature:

When members of the ```Adapter``` interface call the function ```FetchSpecs```, the expectation is an error will be returned and processed.  But as of https://github.com/openshift/ansible-service-broker/pull/682, we are only returning an error from the local_openshift adaptor and none of the others.

We should consider redefining the Adaptor interface function to better fit the result from ```FetchSpecs``` or better define errors from ```FetchSpecs```.

```go
type Adapter interface {
   ...
   FetchSpecs([]string) ([]*apb.Spec, error)
}
```

**Comment by jmrodri** [comment]
Related to this Bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1541524
