### ISSUE TITLE
Should consider using pkg/errors 

### ISSUE THREAD

**Issue by shawn-hurley** [openshift/ansible-service-broker#717]
We should consider using the [errors](https://github.com/pkg/errors) package to wrap errors and keep the context of errors as they are bubbled up. 

> I would actually suggest moving to https://github.com/pkg/errors for this kind of thing. It is very useful. Has a method
errors.Wrap(err,"some additional context")
that returns an error. It also provides the benefit of providing stack traces when the errors are logged with %+v

@maleck13 suggested this while [commenting](https://github.com/openshift/ansible-service-broker/pull/716#discussion_r165410580) on #716 

I think a simple proposal of how this would be used, and how we would go about adding it to our codebase is something that should be considered.

**Comment by maleck13** [comment]
I have used this package many times. It has a small footprint but provides great value.

**Comment by eriknelson** [comment]
> I think a simple proposal of how this would be used, and how we would go about adding it to our codebase is something that should be considered.

Sounds good to me. I would prefer not to have to manually wrap errors all the time; some sugar to make this simple would be my desire.

Love the stack traces!
