### ISSUE TITLE
Broker needs more robust error passing between broker methods and the handlers

### ISSUE THREAD

**Issue by eriknelson** [openshift/ansible-service-broker#730]
The way we're passing errors back from the broker layer to the handlers is not very flexible and should be improved. Today, the handlers basically just switch on the error string contents to detect which type was returned, but this doesn't leave any room for variability in the descriptions passed to the platform.

We need to start thinking about broker error types, preferably OSB centric. High level OSB Errors types should be defined so the broker can return them and the right thing just happens at the HTTP layer. Right now, we're employing the bad habit of extending `broker.go` return signatures to continue to report additional values.

My desire is to be able to flexibly introduce a new `BrokerError` type that a `broker.go` returns in the event of a semantic error, and have the handler layer generically understand how to deal with that. It probably involves some set of methods like `StatusCode()`, `Description()`, etc.

**Comment by eriknelson** [comment]
I'm happy to take this one one, because it always bugs me :)

**Comment by jmrodri** [comment]
Closing as won't fix.
