### ISSUE TITLE
Discussion: Broker should not fail hard when registry names collide 

### ISSUE THREAD

**Issue by shawn-hurley** [openshift/ansible-service-broker#753]
Currently, when a user has two registries defined that are the same name, we will not continue to run. The broker will panic with an error about the registry names are not unique. 

There has been questions and concerns about the current behavior. There has been interest in other ways of handling this use case, I wanted to keep track of this discussion for later.

**Comment by rthallisey** [comment]
Does it matter if the ```name``` is not unique?
Do we use ```name``` as a key for the adaptor?
Should we use a uuid to reference adaptors making ```name``` irrelevant?

Maybe as a first pass on this we can log that a registry was skipped because of a conflicting name.  For a more involved solution we can evaluate how ```name``` is used.

**Comment by shawn-hurley** [comment]
It does matter if the name is not unique, this is what is making sure that FQnames do not collide and overwrite each other in our etcd. 

The name is used to create the FQname and the ID(which is a hash of the FQname) so that we can make sure things are unique and we do not have some very odd issues where APBs don't show up in the catalog because they are overridden. 

Using a UUID was discussed. UUID needs to be gettable on bootstrap of the broker otherwise you will not be able to pull specs for instances that we created with the same broker because now the specs have different IDs.

The big concern is still, the Spec ID is the FQname hash. This must be unique and gettable across broker restarts/bootstraps. 

One way that we may be able to calculate an FQname now is

`registry-address`+`apb-image`+`tag`. 

vs

`registry-name`+`apb-image`+`tag`

Right now if you have two docker hub adapters pointing to same repo/tag then we would get two APBs in the service catalog, the above would not do that instead we would only get a single APB in the service catalog. I think that this might be more sane behavior but is a departure from the current behavior.

**Comment by rthallisey** [comment]
Thanks for providing the details @shawn-hurley.

I think to track a unique APB we need ```registry-address + org + apb-image + tag```. With ```registry-address+apb-image+tag``` I think you can still have different orgs.

**Comment by jmrodri** [comment]
closing won't fix. This problem does exist, but no one has run into it. The broker relies heavily on the registry names being unique, we will continue to fail if you misconfigure the broker.
