### ISSUE TITLE
APB Package should have a sub package for Errors

### ISSUE THREAD

**Issue by shawn-hurley** [openshift/ansible-service-broker#782]
# Feature
We should consider a package for `APB` errors. This would be helpful because packages that the APB package uses can return errors that the `APB` package can understand and pass along to the consumers of the APB package. This will also allow us a place to add methods for things like `IsAPBError()` and return an `APBError` struct that could have more info about the error that a consumer could retrieve. 

An example this will allow the `runtime` to package to return errors that the `APB` package can pass along. 

I suspect that a proposal for this might be helpful outlining the methods, initial errors and any structs/interfaces for this package.

These are just thoughts that were sparked by comments made by @rthallisey on #775

**Comment by eriknelson** [comment]
Love this. A suite of semantic APB errors is a necessity for anyone consuming `libapb`. Most notably, our broker.

**Comment by shawn-hurley** [comment]
Closed in favor of automationbroker/bundle-lib#111
