### ISSUE TITLE
Runtime package needs to expose methods to change the Provider

### ISSUE THREAD

**Issue by shawn-hurley** [openshift/ansible-service-broker#783]
# Feature:
Currently, you instantiate a new runtime with the method `NewRuntime` and this gives you the default runtime. We should add the ability to set/change the runtime to a user-provided runtime.

**Comment by eriknelson** [comment]
I'm unsure that users need to be able to override an entire runtime. In the context of our discussion the other day, my desire is that we should have an API supported way for folks to override their credentials CRUD.

**Comment by rthallisey** [comment]
Action item: Need a document explaining how to create a new Runtime provider.  It makes sense to have as part of explaining what APIs the broker has.

**Comment by eriknelson** [comment]
I think the key feature here is to present controlled ways to alter specific aspects of a "runtime". Use-case: I want to use the majority of the default behavior for the APB runtime, but I want to use a different credential storage.

**Comment by shawn-hurley** [comment]
Also apart of this is adding methods to override the CreateSandbox/DestroySandbox methods. not just mutate them with the hooks, but to completely override them. 

I also think another task here is moving the Running of apb to the runtime in an overridable fashion as well.

**Comment by eriknelson** [comment]
This is germane to the entire discussion around `libapb`. @shawn-hurley I know we wanted to add something to track them, possibly an issue label. We should add something to group all the items that are coming up, and then maybe hold a meeting to discuss when and how we want to split this out.
