### ISSUE TITLE
Users of the executor hook actions should be forced to only use the action once.

### ISSUE THREAD

**Issue by shawn-hurley** [openshift/ansible-service-broker#798]
### Bug:
Currently a user could call `finishWithError` and then call `finishWithSuccess` on the executor. 

**What happened**:
Success overwrote the error.

**What you expected to happen**:
Once finish is called, we should not be able to call another finish action.

**Comment by jmrodri** [comment]
I don't think it should be an error condition that could cause things to go bad on the sender side. I'd rather log the error that we detected a success following an error and possibly print out the caller information we might have. Then we should fix the caller to not do that.

I would probably prevent the overwrite though while doing the logging.

**Comment by jmrodri** [comment]
Closing, hasn't been an issue.
