### ISSUE TITLE
Consider a configuration switch that will execute APBs in ansible verbose mode for debugging purposes.

### ISSUE THREAD

**Issue by eriknelson** [openshift/ansible-service-broker#822]
Came up on the CEE call. SSIA.

**Comment by shawn-hurley** [comment]
I think that this should be a generic flag, that tells a bundle to run in verbose mode and the base for that bundle know's how to translate that?

**Comment by eriknelson** [comment]
@shawn-hurley what do you mean generic flag? something other than a setting in the configmap? Was thinking something like `_apb_verbose_output` and the base would tack on `-vvv` in its presence.

**Comment by shawn-hurley** [comment]
I was thinking something like `_bundle_verbose_output`.

**Comment by eriknelson** [comment]
Ah right. That's more correct, I would just request that we update all of the flags so things remain consistent, which is probably 2 PRs.

First: move from _apb -> _bundle, which means updating docs and images. Then add this flag in a follow up.

**Comment by jmrodri** [comment]
Funny, I thought it would be cool to have an endpoint on the broker that could have it dump debug information as well. I'll formulate a better idea and create an issue for this scenario.

**Comment by rthallisey** [comment]
execute ansible with ```-vvvvvv```

**Comment by jmrodri** [comment]
```
[09:53] <@jmrodri> or is it purely a pass through to the bundle?
[09:53] <@ernelson> jmrodri: I think it's a passthrough
[09:53] <@shurley> +1
```

**Comment by eriknelson** [comment]
See ansible `-vvv` flag.

**Comment by mhrivnak** [comment]
During the IRC meeting just now, it was agreed that this should be a generic setting that is not ansible-specific. Lots of things have a verbose mode and could make use of this flag. Suggested actions:

* add the setting to the bundle contract document
* define that a service bundle should make a best effort to generate verbose output when the setting is true

**Comment by djzager** [comment]
Just wanted to point out in here. That one of the things I learned from the helm registry adapter experiment, creating Specs from scratch, is that it is possible for us to add (from the broker) this verbose flag as a parameter to all plans such that Service Bundle Developers would not have to explicitly add this as a parameter.

Example:
```
apb.ParameterDescriptor{
    Name:            "verbose",
    Title:               "Verbose",
    Type:              "boolean",
    Default:           false,
    Updatable:      flase,
    Required:        false,
},
```

**Comment by jmrodri** [comment]
@djzager this looks very useful, how hard do you think it would be to implement this?
