### ISSUE TITLE
Expose the name of the service binding to the bind role

### ISSUE THREAD

**Issue by pb82** [openshift/ansible-service-broker#866]
## Feature: Expose _apb_service_binding_id to the bind role

**What happened**:

Currently the provision role has access to the ID of the service instance (_apb_service_instance_id). This is useful in cases where we need to label the service instance and make it discoverable.

Something similar would be useful for the bind role. Bind creates a `serviceBinding` instance with a non-deterministic name. In order to trigger `unbind` one has to delete this service binding object. This can be done via the UI.

But suppose you want to trigger `unbind` externally. There is currently no way to know which service binding to delete.

**Proposed solution**: pass in the ID/name of the service binding to the `bind` role as (_apb_service_binding_id / _apb_service_binding_name). 

Example use case: `bind` creates a config map that represents an external resource. When this config map is deleted we also want to delete the binding (trigger unbind). It would be good to have a way to link back from the config map to its respective service binding.

Hope this makes sense.
ping @maleck13

**Comment by maleck13** [comment]
This seems a reasonable things to me and simple to implement. @jmrodri @eriknelson are you ok with the binding id being passed to bind action as part of the params?

@pb82  Assuming this broker change is ok with the team, this could be a good issue for you to contribute a PR for. The areas that would need to change are here
https://github.com/openshift/ansible-service-broker/blob/master/pkg/broker/broker.go#L850 
to add a key to the params map for the bindinguuid 
And also add new constant for the param itself 
https://github.com/openshift/ansible-service-broker/blob/master/pkg/broker/types.go#L34

**Comment by pb82** [comment]
@maleck13 Yes, i'm happy to send a pull request if the ASB team is ok with the proposed solution.

**Comment by shawn-hurley** [comment]
👍 I think this makes sense and a PR would be awesome!

**Comment by jmrodri** [comment]
@maleck13 @pb82 yes, this is okay. I'm honestly surprised we don't already do this :)

**Comment by shawn-hurley** [comment]
closed with #883
