### ISSUE TITLE
bootstrap does not log successful images

### ISSUE THREAD

**Issue by mhrivnak** [openshift/ansible-service-broker#869]
**This form is for bug reports and feature requests. Major features will go through a [spec process](https://github.com/openshift/ansible-service-broker/blob/master/CONTRIBUTING.md).**

**What happened**:
I bootstrapped the broker (built from current master branch), and I did not see any log output summarizing what bundles were successfully discovered. I think this might be a regression, based on memory.

**What you expected to happen**:
See some log output at INFO level summarizing what bundles were successfully discovered.

**How to reproduce it**:
Bootstrap the broker and look at the log output.

**Comment by alaypatel07** [comment]
The [pr](https://github.com/openshift/ansible-service-broker/pull/1008) gives logging information as follows:
1. For each spec, it logs whether the specs needs to be added or updated in datastore.
2. For each spec that needs to be added or updated, it logs whether the spec is updated or added. [Here](https://hastebin.com/evexivumut.ini) is an example of the logs.

I can changing to language of the logs to:
1. `add spec: spec_id to datastore`
2. `update spec: spec_id in datastore`

and submit a follow up PR

**Comment by alaypatel07** [comment]
@jmrodri @mhrivnak [This](pr) should be enough to logs successful images.

**Comment by jmrodri** [comment]
Fixed by PR #1022
