### ISSUE TITLE
Update contributing guide to call out submitting a proposal for large features

### ISSUE THREAD

**Issue by jwmatthews** [openshift/ansible-service-broker#871]
We should update our contributing guide so it clearly informs new contributors that we recommend submitting a proposal to gather feedback prior to feature development.

https://github.com/openshift/ansible-service-broker/blob/master/CONTRIBUTING.md#submitting-changes-to-ansible-service-broker

Also should call out the proposal template to help with drafting the proposal
 https://github.com/openshift/ansible-service-broker/blob/master/docs/proposals/proposal-template.md

Along with examples of former proposals at
  https://github.com/openshift/ansible-service-broker/tree/master/docs/proposals

**Comment by jmrodri** [comment]
The `CONTRIBUTING.md` already mentions the proposal process: https://github.com/openshift/ansible-service-broker/blob/master/CONTRIBUTING.md#major-features
