### ISSUE TITLE
Docker Distribution isn't supported as a Ansible Service Broker registry

### ISSUE THREAD

**Issue by Jmainguy** [openshift/ansible-service-broker#877]
## Feature:
The number and types of Ansible Service Broker Registrys that are supported are very limited. Our company would like to use Jfrog's Artifactory, but at a minimum, I would hope that a regular v2 distrubution end point would be supported. Would be great if you added v2 distrubution as supported registry fro Ansible Service Broker

**What happened**:
Tried using ansible service broker registry, was dissapointed when I could not
**What you expected to happen**:
I expected it to support docker distribution/registries, like pulp, or docker distribution, or jfrog aritfactory.
**How to reproduce it**:
Try and use any regular v2 docker distribution endpoint, it isnt currently supported.

**Comment by jwmatthews** [comment]
We use the Docker v2 Catalog API for discovery.  If a registry supports that... than we have the big pieces we need for the adapter to function.

We have not tested against JFrog Artifactory before.
According to https://www.jfrog.com/jira/browse/RTFACT-8206 they support _catalog API endpoint.

@Jmainguy if you would provide us with a registry endpoint to test against we can try to get an adapter working.

**Comment by Jmainguy** [comment]
You should be able to hit this endpoint now.
```/bin/bash
curl https://jmainguy-docker-local.jfrog.io/v2/_catalog -u anonymous:anonymous
```
https://jmainguy-docker-local.jfrog.io/v2/_catalog

**Comment by jmrodri** [comment]
Fixed by a bunch of PRs to bundle-lib
https://github.com/automationbroker/bundle-lib/pulls?q=is%3Apr+apiv2+is%3Aclosed

**Comment by Jmainguy** [comment]
Yall are the best, thank you for working on this.
