### ISSUE TITLE
Allow pod termination log to be configured to allow a clear error message on exit

### ISSUE THREAD

**Issue by maleck13** [openshift/ansible-service-broker#889]
## Feature:
When a pod exits, the termination log is checked to for a message and the pod status updated with this message if it is present. The default location is /dev/termination-log however you cannot write to this location from within the APB pod. 
If we made the location of the termination log configurable then a ServiceBundle developer could write a user friendly error to this location and as we check it in https://github.com/automationbroker/bundle-lib/blob/master/runtime/watch_pod.go#L146 it would make its way back to the user. 
It maybe an option to create a ASB module for making this as simple as possible for the developer.

ping @shawn-hurley

**Comment by shawn-hurley** [comment]
I almost think a very quick proposal would make sense for this one. I think that we may want to allow the apb to specify where they will be printing out the termination log and should be an update to the apb spec. @dymurray @djzager @mhrivnak

**Comment by mhrivnak** [comment]
I also made an APB write a message automatically to `/dev/termination-log`, and I see that message in the output of `oc describe pod` in the `Containers.apb.State.Message` attribute.

**Comment by mhrivnak** [comment]
I think I found the problem you likely hit. I tried using the `lineinfile` module, which tries to create a temporary file in the same directory as the file being written to. The error message was:

```
The destination directory (/dev) is not writable by the current user. Error was: [Errno 13] Permission denied: '/dev/.ansible_tmpF36YNStermination-log'
```

**Comment by mhrivnak** [comment]
The solution is to use the `unsafe_writes` option of the `lineinfile` module. Here is an example (thanks to @dymurray who was the brain behind what's below):

```
- name: do something
  shell: "/bin/false"
  register: somethingout

- lineinfile:
    line: "There was an error. <insert helpful info here>"
    path: "/dev/termination-log"
    unsafe_writes: true
  when: somethingout.rc != 0

- fail:
    msg: "There was an error. <insert helpful info here>"
  when: somethingout.rc != 0

**Comment by shawn-hurley** [comment]
I also think that @johnkim76 might have some thoughts as he implemented https://github.com/openshift/ansible-service-broker/pull/837

**Comment by johnkim76** [comment]
SGTM... I agree with @shawn-hurley that we should update the apb spec to make this configurable in APBs

**Comment by mhrivnak** [comment]
> SGTM... I agree with @shawn-hurley that we should update the apb spec to make this configurable in APBs

I think we should define the use case concretely for why this needs to be configurable. Is it just:

"As an APB author, I want to create temporary files in the same directory as the termination log so I can use ansible's `lineinfile` module without setting `unsafe_writes=true`" ?

Are there other use cases?

**Comment by johnkim76** [comment]
@mhrivnak I too had no issues while I was demoing this via my simple APB (here)[https://github.com/johnkim76/lastop-cem-demo-apb/blob/master/roles/provision-lastop-cem-demo-apb/tasks/cem.yml#L9].  My thought was that making this configurable may not be a bad idea since the (allows)[https://kubernetes.io/docs/tasks/debug-application-cluster/determine-reason-pod-failure/] the `/dev/termination-log` path to be configurable.

**Comment by maleck13** [comment]
@mhrivnak I am happy with your solution here. The main usecase was to allow a clear error message to be returned to the user from an APB. Once the location can be written too, I am not sure on the advantage of making it configurable and updating the Spec to allow it.

**Comment by shawn-hurley** [comment]
I am also ok with not making this configurable. @mhrivnak thoughts?

**Comment by mhrivnak** [comment]
> I am also ok with not making this configurable. @mhrivnak thoughts?

I would leave it as-is unless there is a concrete use case that demonstrates value in making it configurable. I don't think we've seen such a use case yet.
