### ISSUE TITLE
asb-etcd pod not found 

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [openshift/ansible-service-broker#893]
**This form is for bug reports and feature requests. Major features will go through a [spec process](https://github.com/openshift/ansible-service-broker/blob/master/CONTRIBUTING.md).**

## Bug:

As part of https://github.com/openshift/ansible-service-broker/blob/master/docs/debugging.md, I see two pods created. But in my setup I cannot see asb-etcd pod ? 
Is this still valid in oc v3.9.14 ??

```
$ oc get pods
NAME               READY     STATUS    RESTARTS   AGE
asb-1-wtd6f        1/1       Running   0          6m
asb-etcd-1-j9zgz   1/1       Running   0          6m
```
```
# oc version 
oc v3.9.14
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.9.14
kubernetes v1.9.1+a0ce1bc657

```

**Comment by djzager** [comment]
This all depends on how you deployed the broker. If you are using our latest upstream templates (ie. catasb or run_latest_build) the broker will be deployed configured to use CRDs for saving state.

We probably should look through our docs.

**Comment by SaravanaStorageNetwork** [comment]
@djzager  yes mostly this looks like a doc. bug. doc. should be updated that etcd pod is applicable only if etcd is used.
