### ISSUE TITLE
Incorrect version check in run_latest_build.sh

### ISSUE THREAD

**Issue by beekhof** [openshift/ansible-service-broker#912]
## Bug:

**What happened**:

# ./run_latest_build.sh
++ oc version
++ head -1
+ version='oc v3.7.23'
++ echo oc v3.7.23
++ egrep -o 'v[0-9]+(\.[0-9]+)+'
++ tr -d v.
+ client_version=3723
+ '[' latest '!=' latest ']'
+ ((  3723 >= 3100  ))
+ oc cluster up --image=docker.io/openshift/origin --tag=latest --enable=service-catalog,template-service-broker,router,registry,web-console --routing-suffix=172.16.1.70.nip.io --public-hostname=172.16.1.70.nip.io
Error: unknown flag: --tag

[...]
+ '[' 1 -ne 0 ']'
+ echo 'Error starting cluster'
Error starting cluster
+ exit

**What you expected to happen**:

Script uses the correct flags

**How to reproduce it**:

Run ./run_latest_build.sh with oc v3.7.23

**Comment by jmrodri** [comment]
@beekhof  thanks we'll look at this one soon. For now, you could update the version check to be 3723 to let you run with the 3.7.23 until we have a patch for this script.

**Comment by jmrodri** [comment]
The current rpmvercmp.c file
https://github.com/rpm-software-management/rpm/blob/master/lib/rpmvercmp.c

**Comment by jmrodri** [comment]
I think in order to make this fool proof we're going to have to parse the string field by field. Otherwise, we're always going to run into a problem.

**Comment by djzager** [comment]
I believe the _best_ resolution to this is for us to simply remove the `oc cluster up` from the `run_latest_build`.
