### ISSUE TITLE
What is the meaning of AA in the documentation, other acronyms are explained

### ISSUE THREAD

**Issue by petenorth** [openshift/ansible-service-broker#917]
## Bug:

**What happened**:

Reading https://github.com/openshift/ansible-service-broker/blob/master/docs/design.md it is unclear what AA stands for.

**What you expected to happen**:

The the acronym AA is explained at least once

**How to reproduce it**:

N/A

**Comment by eriknelson** [comment]
@petenorth AA was the old name for APB. Looks like the definition was updated in this doc, but not the acronyms. Fixed with the above PR. Hope that helps.
