### ISSUE TITLE
run_latest_build.sh fails to start a cluster with the broker installed

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/ansible-service-broker#931]
**This form is for bug reports and feature requests. Major features will go through a [spec process](https://github.com/openshift/ansible-service-broker/blob/master/CONTRIBUTING.md).**

## Bug:

The `./run_latest_build.sh` script provided in the README.md for `oc cluster up` fails to start a cluster.

**What happened**:

Running `./run_latest_build.sh` either locally on OSX, or in a `fedora` VM running on OSX ends with the following:

```
FAIL
   Error: failed to start the template service broker apiserver: timed out waiting for the condition

Error starting cluster
```

Checking the logs lists many many api calls:

```
I0504 20:36:51.955807    4087 round_trippers.go:436] GET https://127.0.0.1:8443/apis/extensions/v1beta1/namespaces/openshift-template-service-broker/daemonsets/apiserver 200 OK in 1 milliseconds
```
It appears to be polling and searching for something to change, but ultimately failes with `timed out waiting for the condition`, which is fairly vague.

**What you expected to happen**:

The cluster would start & the broker would be installed.

**How to reproduce it**:

Run the script, nothing unique or interesting to add (except perhaps a `--loglevel=10`)

In addition, I found that `export MINISHIFT_ENABLE_EXPERIMENTAL=y` and `minishift start --service-catalog` also fails to work. Docs [here](https://github.com/minishift/minishift-addons/tree/master/add-ons/ansible-service-broker). 

Version for reference:

```
oc version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

**Comment by benjaminapetersen** [comment]
More detailed:

```bash 
[vagrant@openshift-fedora-vm ~]$ ./run_latest_build.sh
Using nsenter mounter for OpenShift volumes
Using 127.0.0.1 as the server IP
Starting OpenShift using docker.io/openshift/origin:latest ...
-- Starting OpenShift container ...
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ...
   scc "privileged" added to: ["system:serviceaccount:default:registry"]
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Importing internal templates ... OK
-- Installing service catalog ... OK
-- Installing template service broker ... FAIL
   Error: failed to start the template service broker apiserver: timed out waiting for the condition

Error starting cluster

```

**Comment by djzager** [comment]
@benjaminapetersen It looks like you are having issues with `oc cluster up`. Looking at #920, you'll see that we are removing the `oc cluster up` portion from these `run_latest_build` scripts. The reason for this is that there are a multitude of ways for you to bring up a cluster and we aren't experts in `oc`. Your best bet is to check out https://github.com/openshift/origin/issues for help with bringing up a cluster with the `3.9` client.

**Comment by benjaminapetersen** [comment]
@djzager I think I'm rolling now.  This issue is probably most relevant to the last line of what I posted above:

```
Error: failed to start the template service broker apiserver: timed out waiting for the condition
```

It would be great if "the condition" could be made more clear.  

Thanks!
