### ISSUE TITLE
Play nice with kube2iam by allowing annotations be set on the child job pods created by ASB

### ISSUE THREAD

**Issue by pvdvreede** [openshift/ansible-service-broker#932]
## Feature:

Wondering if there were any opinions on if ASB can be used to provision AWS resources like RDS etc? We use Kubernetes with kube2iam to grant AWS IAM Roles at the pod level. It would be nice to use this with ASB, but I note that the provisioning/depovisioning jobs etc take place in a separate job pod than the ASB is run from. This means that the kube2iam annotations on the ASB pod would not be used when trying to create an RDS instance for example and would fail.

Is there a way to specify annotations that should be placed on the job pods? Or can the annotations from the ASB pod be copied onto any job pods it creates?

Thanks.

**Comment by rthallisey** [comment]
@pvdvreede This is an interesting use case. My understanding is that every pod/daemon-set/replication-controller launched will need the annotation in order to work:
```yaml
      annotations:
        iam.amazonaws.com/role: role-arn
```
One way I think we can hand this is by adding a config option to the broker that allows the user to determine an annotation passed down as an environment variable to the APB.  The apb picks it up and adds it to every resource.
 - Create a mechanism to apply labels/annotations to every resources an APB creates.
 - Create a config variable to change/append to the default set of labels/annotations for APB resources.

There's also the rds-postgrees-apb:
https://github.com/ansibleplaybookbundle/rds-postgres-apb

**Comment by shawn-hurley** [comment]
@rthallisey @pvdvreede I think that this is a wider feature about how the APB can transparently add annotations / keep track of added resources. I would really love with investigated sidecars[https://kubernetes.io/docs/concepts/cluster-administration/logging/#sidecar-container-with-a-logging-agent] or some other mechanism so that each bundle (regardless of the bundle base) could get this feature. 

I think it might be worth discussing in the community meetings, I added it to the agenda here: https://docs.google.com/document/d/1Mj7bVYJ8NK-TwU_mxeZLprmBBZZ-xOq-Hg4CiD3E6pM/edit#

**Comment by pvdvreede** [comment]
@shawn-hurley thanks for running with it, was there outcome of the discussion at the community meeting as to how you might proceed?

**Comment by shawn-hurley** [comment]
@pvdvreede IIRC we discussed it and we decided to table this for now. at least until the next meeting. I think people wanted to research sidecars more effectively.

But I think a major point that came out of the discussion is a question. Sorry, should have posted here earlier. Is your APB itself the resource that needs the annotation or is it some other resource that you created that needs the annotation to talk to an AWS resource? 

I actually think both cases are valid and need to be solved so they are both part of the discussions but we did want some clarity

**Comment by pvdvreede** [comment]
Sure, thanks.

To your question, it is the APB itself - an example being that we want to run the AWS RDS APB (https://github.com/awslabs/aws-servicebroker/tree/master/templates/rdspostgresql) or variation of it. When I tested this I noticed that the ASB will run the APB in a k8s Job Pod in a different namespace. I saw that the Job Pod had edit permissions for the namespace the service instance CRD was created in - so for creating apps in Kubernetes or adding a metrics exporter there, everything is AOK 👍 

However, our use case is to provide services like a Database, but leverage AWS RDS's services for that and hook it into Kubernetes. So the Job Pod needs to have an AWS IAM Role and we dont want all the Nodes that _could_ run the Job Pod to have that elevated access - and would rather restrict it with Kube2iam to just that specific Pod. 

So the long and short of it is that the Job Pod that is executing the APB needs the `iam.amazonaws.com/role: role-arn` annotation. Certainly it is easy for me to add the annotation to the ASB pods themselves as those are deployed by me - it is just the Pods that are dynamically created _by_ the ASB that would need the configuration.

**Comment by shawn-hurley** [comment]
Thanks for the clarification, I'll update the issue after the next community meeting.

**Comment by cspargo** [comment]
we are also finding this to be an issue. The security implications of having all nodes with permissive IAM roles make it unusable for us. If we could add annotations to use kube2iam, we could control it, or even adding nodeselectors and tolerations to the pod spec would help a lot.

If i'm reading things right, it seems like we would be needing a way to customize the spec here https://github.com/automationbroker/bundle-lib/blob/d86f8bb04dd1f8ac69cd58bae38716ed8180a065/runtime/run_bundle.go#L85

**Comment by shawn-hurley** [comment]
Sorry @pvdvreede and @cspargo this issue has slipped off my radar.

The above is correct.

If either of you would like to add a proposal of some sort for this case (adding specific annotations in some configurable way to the bundle pod). If your not really interested in a proposal and just want to contribute the code we could catch up and I could write up the proposal and have you implement? 

I think if we keep the scope to just the bundle PR and not any of the resources it creates then we could move this use case forward. @jmrodri @eriknelson @rthallisey Any chance you guys have strong feelings on the above that we should take into account early on?

**Comment by cspargo** [comment]
I think having the ability to specify an IAM role ARN in a kube2iam specific pod annotation, would cover both our requirements.  This would trigger the addition of an annotation like this, with "role-arn" set to the ARN of the IAM role.

```
kind: Pod
metadata:
  annotations:
    iam.amazonaws.com/role: role-arn
```

I'm way out of my depth here, but I think this is probably a cluster level config and would be a field added to the broker config yaml. I guess under the "openshift" section,along with "sandbox_role" and "keep_namspace". If it's kept specific to this purpose, maybe a new field "kube2iam_role" set to the ARN. A more generic parameter might be "pod_annotations", containing a list of keys and values.

For that to be passed through to the pod creation job, I guess the "ExecutionContext" struct in bundle-lib would need to be extended.

I can see another potential situation where people might not use kube2iam and instead want to control which nodes in a cluster the pods will be launched on. For example, they might have a set of privileged nodes in the cluster with elevated IAM policy (e.g. the master nodes). That would usually be done with node selectors and tolerations added to the pod's spec. That would probably need a way to pass a structure through that's appended to the pod spec. For example, to force the pods to the master node(s):


```
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
        value: ''
```

**Comment by cspargo** [comment]
i've realised there are still issues with using kube2iam/kiam. Normally a whitelist of IAM roles would be added as an annotation to the namespace that pods were being launched into, to control which IRAM roles they could use. Since these apb pods are launched into a temporary random namespace, we couldn't add that annotation beforehand. The broker would also need to handle adding annotations to the "sandbox" namespaces.

**Comment by shawn-hurley** [comment]
@cspargo I have not used kube2iam so I don't know how it works or how to complete the use case. From the above I am seeing there might be two things that we need to do.

1. We need to add configuration options to the broker/bundle-lib to allow a administrator to specify arbitrary annotations or labels to a transient(namespace the broker creates) namespace.
2. We need to add configuration options to the broker/bundle-lib to allow an administrator to specify arbitrary annotations or labels to a APB pod.

@pvdvreede @cspargo would the above solve your use case? It sounds like it might.

Open questions I have
1. Should the APB be able to say it needs the existence of the annotation to function? does this make sense?
2. Should an administrator be able to tie the labels/annotations to a specific APB? Or maybe a registry? 

@dymurray @djwhatle @johnkim76 Do you guys have any thoughts?

**Comment by pvdvreede** [comment]
@shawn-hurley thanks for thinking on this - I believe the two things you think we need to do are correct.

As for your questions:
1. This sounds like a good idea as if the APB is to create an RDS instance, it would be impossible to do without the Role. 
2. This is a good question, and something I had not thought of, but yes, given each APB might need different access to AWS depending on what it does, it would be best to allow each APB to specify a separate role. For example an APB that creates RDS instances should run with a role that only has access to RDS. If there is a separate APB that needs access to S3 then it should use a different role as it does not need RDS access.

So it seems like a good idea to be able to set a AWS IAM Role ARN for each APB and have that role name be added with the kube2iam key to the annotations for the pod and then have the namespace the APB pod runs in have an annotation for: 
```
iam.amazonaws.com/allowed-roles: |
      ["<role arn>"]
```

**Comment by cspargo** [comment]
Yes that seems right. Be aware that "kiam" is an alternative to kube2iam that seems to be gaining popularity. It uses the same annotation on pods, but a different annotation on the namespace:

```
kind: Namespace
metadata:
  name: iam-example
  annotations:
    iam.amazonaws.com/permitted: ".*"
```

so it probably makes sense to support arbitrary annotations on the transient APB namespaces.

**Comment by pvdvreede** [comment]
Any more news on this issue? I would be happy to take a look and see if I can wrangle a PR for the changes... Just looking for a bit of guidance of how/where to change things and how the owners of this repo think it should be solved...

**Comment by pvdvreede** [comment]
Am I correct in thinking the best way to implement this is to take some of the `apb.yaml` key values under the `metadata` key and set them as annotations? Currently all metadata key values are being set as labels, so is it a good idea to instead have any key starting with `annotation__` be set as an annotation instead of a label, eg `annotation__xxx: abc` would set the annotation `xxx: abc` on the pod?

This way the annotations will be configurable from each apb and there is nothing specific to kube2iam anywhere... Is it also possible to set those labels and annotations on the namespace as well as the pod, which would also solve the restrictions problem...

**Comment by pvdvreede** [comment]
Sorry, another thought - rather than adding annotations to namespaces, are we able to configure ASB to use a single namespace for all Jobs, so that we can pre-create the namespace with whatever labels/annotations we want, then tell the ASB that all jobs should be run in that namespace?

Was there technical reasons as to why the ASB will generate a new namespace for every Job it runs? Maybe to make cleanup easier by deleting the whole namespace than needing to cleanup every resource it creates? 

Having the namespace pre-created also means the ASB does not need as much privileges eg, the create/delete namespace privilege...

**Comment by shawn-hurley** [comment]
@pvdvreede think that this idea of pre-setting the transient namespace to a single namespace should be a fairly simple change. I think that we are in a feature freeze right now so this might have to wait till we branch the release code. @jmrodri @eriknelson is that correct? Wondering your thoughts on the above?

**Comment by pvdvreede** [comment]
Would you accept a PR to make a static job namespace optional flag to the ASB?

**Comment by jwmatthews** [comment]
@pvdvreede would welcome a PR, best steps would to submit a proposal with your thoughts then we can review and offer comments.
