### ISSUE TITLE
Lock Mechanism in DAO 

### ISSUE THREAD

**Issue by shawn-hurley** [openshift/ansible-service-broker#951]
Currently, we are adding a lock in the DAO to sync access to a resource. I think that we need to consider other options that are more in line with kubernetes.

@eriknelson  mentioned resource generation reconciliation that he has seen in the service catalog.

I think that moving to some sort of caching/informer mechanism might be a way to go.

PR where change was introduced: #947

**Comment by maleck13** [comment]
👍  I think the locking mechanism is ok, but limited as it means you cannot scale the broker beyond a single replica
