### ISSUE TITLE
Rebuilding and pushing apb shows 2 apb

### ISSUE THREAD

**Issue by vatsalparekh** [openshift/ansible-service-broker#958]
## Bug:

**What happened**:
Rebuilding an apb and pushing it to broker, seeing 2 apb of the same name, so can't distinguish between them which one is the new and correct one
**What you expected to happen**:
The old one to go maybe?
**How to reproduce it**:
Make changes and push the new apb to the broker

**Comment by vatsalparekh** [comment]
seeing this when trying [import-vm-apb[(https://github.com/ansibleplaybookbundle/import-vm-apb)

**Comment by djzager** [comment]
The broker, by default in OpenShift, is configured to look in 2 places for APBs.

1. https://hub.docker.com/r/ansibleplaybookbundle/ all the images with `latest` tag
1. For images in the `openshift` namespace matching this regex `".*-apb$"`

When you use the APB tool to build and push to the broker, you are actually creating an image in the `openshift` namespace. So now there are two APBs that just so happen to have the same name. There really isn't anything for us to do here. You can 1) not use the dockerhub registry (kind of lame) or 2) change the `displayName` in [`apb.yml`](https://github.com/ansibleplaybookbundle/import-vm-apb/blob/master/apb.yml#L9) like:

```diff
metadata:
-  displayName: Import Virtual Machine
+  displayName: (djzager) Import Virtual Machine
  imageUrl: https://cdn.pbrd.co/images/H5Gutd7.png
  longDescription: |
     Import Virtual Machine from an existing image or a VMware environment.
```

I prefer method 2.
