### ISSUE TITLE
Instructions in README doesn't work with OpenShift v3.9

### ISSUE THREAD

**Issue by gaurav-nelson** [openshift/ansible-service-broker#969]
**This form is for bug reports and feature requests. Major features will go through a [spec process](https://github.com/openshift/ansible-service-broker/blob/master/CONTRIBUTING.md).**

## Bug: Instructions doesn't work for OpenShift v3.9

**What happened**: Build script result in an error `Error: unknown flag: --enable`

**What you expected to happen**: Run a cluster with the service-catalog and the Ansible Service Broker running

**How to reproduce it**: 

1. Install latest oc binary from https://github.com/openshift/origin/releases/download/v3.9.0/openshift-origin-client-tools-v3.9.0-191fece-linux-64bit.tar.gz
2. Enable local cluster management prerequisites https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md
3. Run the commands
```
wget https://raw.githubusercontent.com/openshift/ansible-service-broker/master/scripts/run_latest_build.sh
chmod +x run_latest_build.sh
./run_latest_build.sh
```

**Logs**:
```
[root@node ~]# ./run_latest_build.sh
Error: unknown flag: --enable


Usage:
  oc cluster up [options]

Examples:
  # Start OpenShift on a new docker machine named 'openshift'
  oc cluster up --create-machine

  # Start OpenShift using a specific public host name
  oc cluster up --public-hostname=my.address.example.com

  # Start OpenShift and preserve data and config between restarts
  oc cluster up --host-data-dir=/mydata --use-existing-config

  # Use a different set of images
  oc cluster up --image="registry.example.com/origin" --version="v1.1"

  # Specify which set of image streams to use
  oc cluster up --image-streams=centos7

Options:
      --create-machine=false: Create a Docker machine if one doesn't exist
      --docker-machine='': Specify the Docker machine to use
  -e, --env=[]: Specify a key-value pair for an environment variable to set on OpenShift container
      --forward-ports=false: Use Docker port-forwarding to communicate with origin container. Requires 'socat' locally.
      --host-config-dir='/var/lib/origin/openshift.local.config': Directory on Docker host for OpenShift configuration
      --host-data-dir='': Directory on Docker host for OpenShift data. If not specified, etcd data will not be persisted on the host.
      --host-pv-dir='/var/lib/origin/openshift.local.pv': Directory on host for OpenShift persistent volumes
      --host-volumes-dir='/var/lib/origin/openshift.local.volumes': Directory on Docker host for OpenShift volumes
      --http-proxy='': HTTP proxy to use for master and builds
      --https-proxy='': HTTPS proxy to use for master and builds
      --image='registry.access.redhat.com/openshift3/ose': Specify the images to use for OpenShift
      --image-streams='rhel7': Specify which image streams to use, centos7|rhel7
      --logging=false: Install logging (experimental)
      --metrics=false: Install metrics (experimental)
      --no-proxy=[]: List of hosts or subnets for which a proxy should not be used
      --public-hostname='': Public hostname for OpenShift cluster
      --routing-suffix='': Default suffix for server routes
      --server-loglevel=0: Log level for OpenShift server
      --service-catalog=false: Install service catalog (experimental).
      --skip-registry-check=false: Skip Docker daemon registry check
      --use-existing-config=false: Use existing configuration if present
      --version='': Specify the tag for OpenShift images

Use "oc options" for a list of global command-line options (applies to all commands).

Error starting cluster
[root@node ~]# oc version
oc v3.9.25
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO
[root@node ~]# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-63.git94f4240.el7.x86_64
 Go version:      go1.9.2
 Git commit:      94f4240/1.13.1
 Built:           Mon Apr 30 15:45:42 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-63.git94f4240.el7.x86_64
 Go version:      go1.9.2
 Git commit:      94f4240/1.13.1
 Built:           Mon Apr 30 15:45:42 2018
 OS/Arch:         linux/amd64
 Experimental:    false

```

**Comment by shawn-hurley** [comment]
@ron1 If you want a run latest build to work for 3.9 you should use [this](https://raw.githubusercontent.com/openshift/ansible-service-broker/release-1.2/scripts/run_latest_build.sh) run_latest_build is made to work with the latest oc. Which while we are developing is the currently being worked on. The release branch is locked down to always work with that release so the run_latest_build above should work. 

To answer your other question, the APB will deploy the latest broker, that may or may not work on older versions of OC but I think should work on 3.9.

**Comment by gaurav-nelson** [comment]
Thanks @shawn-hurley but the file you shared doesn't work either. Can you point me from where I can get the 3.10 `oc` binary? or do I have to build it myself?

**Comment by djzager** [comment]
@gaurav-nelson If you want the 3.10 oc binary `docker cp $(docker create docker.io/openshift/origin:v3.10):/bin/oc /usr/local/where/you/want/it`. I think in future versions (thinking of 3.11), the origin container will not contain the oc binary. I'm not sure of that but don't want to guarantee it to work forever.

If you have an 3.9 oc binary and want to install the broker you can:

1. Bring up the cluster with the service catalog, some variation of `oc cluster up --service-catalog=true`
1. Make sure you are an admin user with something like `oc login -u system:admin`
1. `curl https://raw.githubusercontent.com/openshift/ansible-service-broker/release-1.1/apb/install.yaml | kubectl create -f -`

At the end of the day, the purpose of the `run_latest_build.sh` wasn't really intended to be something that we maintained in older releases. It's intention was to be a simple onboarding with the latest, in our case that would be 3.10 now. Apologies for any heartache we cause as we try and 1) consolidate how many ways there are to install the broker 2) simplify the installation of the broker into a running cluster by having an APB.

**Comment by djzager** [comment]
> If you have an 3.9 oc binary and want to install the broker you can:
> 
>     Bring up the cluster with the service catalog, some variation of oc cluster up --service-catalog=true
>     Make sure you are an admin user with something like oc login -u system:admin
>     curl https://raw.githubusercontent.com/openshift/ansible-service-broker/release-1.1/apb/install.yaml | kubectl create -f -

Of course after adding that as a comment, I found an issue with release-1.1 apb :sunglasses: . I'm working on a fix now.

**Comment by djzager** [comment]
https://github.com/automationbroker/automation-broker-apb/pull/23 and https://github.com/automationbroker/automation-broker-apb/pull/24

**Comment by gaurav-nelson** [comment]
@djzager Thank you for the instructions. They are working now.
```
[root@localhost ~]# oc get pods --all-namespaces
NAMESPACE                           NAME                                  READY     STATUS      RESTARTS   AGE
automation-broker-apb               install-automation-broker-apb-z8wmx   0/1       Completed   0          12m
automation-broker                   automation-broker-1-ls5lh             1/1       Running     0          10m
automation-broker                   broker-etcd-1-ls8jm                   1/1       Running     0          10m
default                             docker-registry-1-c59n9               1/1       Running     0          15m
default                             persistent-volume-setup-nnfwx         0/1       Completed   0          15m
default                             router-1-tvmfg                        1/1       Running     0          14m
kube-service-catalog                apiserver-f9cd9dc79-rl5g9             2/2       Running     0          15m
kube-service-catalog                controller-manager-697d7cbffd-9mr4v   1/1       Running     0          15m
openshift-template-service-broker   apiserver-4b2cl                       1/1       Running     0          14m
openshift-web-console               webconsole-7dfbffd44d-8tlmj           1/1       Running     0          14m
[root@localhost ~]# svcat get brokers
           NAME                                                        URL                                              STATUS
+-------------------------+-------------------------------------------------------------------------------------------+--------+
  automation-broker         https://automation-broker.automation-broker.svc:1338/automation-broker/                     Ready
  template-service-broker   https://apiserver.openshift-template-service-broker.svc:443/brokers/template.openshift.io   Ready
[root@localhost ~]#

```

**Comment by jmrodri** [comment]
@djzager states this has been addressed.
